### ISSUE TITLE
Cannot read property 'draggable' of undefined at KEditor.setContent

### ISSUE THREAD

**Issue by Dhara-ZYMR** [Kademi/keditor#100]
Hi @ducdhm ,

I have dynamically added multiple keditor instance on my page like: 
$('#editor1').keditor();
$('#editor2').keditor();
$('#editor3').keditor();

(Note: I have not used it like you have in your multiple content area example because when I do getContent , then in that case, I get data of all the content-areas merged, so I cant differentiate html of each content area).

Coming to my issue, I do for loop and get the Content of each content area. I am saving that in my DB.
When I come back to my page and retrieve the data to show it back on page using 'setContent', The data of first content area sets perfectly. But while setting it for second content area it gives me following error:
Cannot read property 'draggable' of undefined at KEditor.setContent on line number 1783 of src/js/keditor.js

While debugging further i was able to figure out that kEditor Object contains only following keys:
body, element, options, windows and __proto__
other keys those related to containerSnippets and similar ones were missing.
This seems to be cause of this error.

Do you have any solution?

Thanks in advance!

**Comment by Dhara-ZYMR** [comment]
@ducdhm any update over this?

**Comment by ducdhm** [comment]
@Dhara-ZYMR About the properties you see in keditor object, the visible keys are properties, methods of keditor are in `__proto__` key. It's new ways Chrome Web Development Tools displays object in `Console` tab

**Comment by Dhara-ZYMR** [comment]
Ya but for second keditor instance on the same page it does not contain properties like componentSnippets, containerSnippets, snippetsComponentCategories and snippetsContainerCategories. It is possibly due to below code: 
if (body.hasClass('initialized-snippets-list')) {
	            flog('Snippets list is already initialized!');
	        } else {
	            ajaxRequest = self.initSidebar();
	            body.addClass('initialized-snippets-list');
	        }

For first instance it is adding the properties but then my body (or snippet div container) has the class already so these properties doesn't append to new keditor object.

Any suggestion to solve this problem?

**Comment by Dhara-ZYMR** [comment]
@ducdhm , Can we dynamically add more ids to contentAreasSelector for having multiple content area?

**Comment by ducdhm** [comment]
@Dhara-ZYMR 
> Can we dynamically add more ids to contentAreasSelector for having multiple content area?
Sorry, we can not :(

**Comment by ducdhm** [comment]
@Dhara-ZYMR I missed this section in your issue:
> (Note: I have not used it like you have in your multiple content area example because when I do getContent , then in that case, I get data of all the content-areas merged, so I cant differentiate html of each content area).

You can get content in array format: `$(target).keditor('getContent', true)`

**Comment by ducdhm** [comment]
Fixed!
