### ISSUE TITLE
inline editing: keditor + x-editable

### ISSUE THREAD

**Issue by orazionelson** [Kademi/keditor#104]
Hello, 
I'm integrating x-editable to in-line edit a page created in keditor.
https://vitalets.github.io/x-editable/
I create a snippet with the script that shows a **select** with field options but the problem is that it doesn't work when I just drag the snippet, I have to save the file before.

How can I make it work at "runtime"?

![schermata da 2018-04-17 11 20 35](https://user-images.githubusercontent.com/113308/38861353-a2d5ad94-4232-11e8-9d15-e62e75d2b6a7.png)

**Comment by orazionelson** [comment]
Load the CSS and the JS:
```
<link rel="stylesheet" type="text/css" href="http://localhost/path/assets/scripts/keditor/plugins/x-editable/dist/bootstrap-editable/css/bootstrap-editable.css" />

<script type="text/javascript" src="http://localhost/path/assets/scripts/keditor/plugins/x-editable/dist/bootstrap-editable/js/bootstrap-editable.js"></script>
```

This is the snippet, I pass everything is possible with data-*

````
<div data-type="component-editable" data-preview="snippets/default/preview/jumbotron.png" data-keditor-title="Editable Jumbotron" data-keditor-categories="Text;Heading;Bootstrap component;">
	<div class="jumbotron">
		<div class="container">	  
			<div class="col-md-12"> 
				<p><a href="#" class="editable" data-value="site_description" data-showbuttons="false" data-source="[{'value':'site_lang','text':'site_lang'},{'value':'site_name','text':'site_name'},{'value':'site_title','text':'site_title'},{'value':'site_description','text':'site_description'},{'value':'site_logo','text':'site_logo'}]" data-type="select" data-pk="1" data-inputclass="form-control">site_description</a></p>
			</div>
		</div>
	</div>
</div>
````

_(If it doesn't work try to change allo single quotes wth entity: **& quot ;** in **data-source**)_

Then just trigger the x-editable in the editor page:
```
<script>
$(document).ready(function() {
	$.fn.editable.defaults.mode = 'inline';
    $('.editable').editable();
});
</script>
```

**Comment by ducdhm** [comment]
@orazionelson You did it wrong mate. To create new component type, you need create your own handler for this component. Please read [this guide](https://github.com/Kademi/keditor#customize-component-type);

**Comment by orazionelson** [comment]
Yes, that's just a first approach, i read the guide and now I'm working on keditor-components file.

I made a new component:
`(function ($) {
    var KEditor = $.keditor;
    var flog = KEditor.log;
    KEditor.components['editable'] = {
...
`
But I can't find the way to trigger the x-editable after the component has been dragged and released on the page :\

**Comment by orazionelson** [comment]
I did It!!!!

`(function ($) {
    var KEditor = $.keditor;
    var flog = KEditor.log;

    KEditor.components['editable'] = {
        options: {
            
        },

		//settingEnabled: true,
        init: function (contentArea, container, component, keditor) {
            flog('init "editable" component', component);
            var componentContent = component.children('.keditor-component-content');
            var editable = componentContent.find('a.editable');
            $.fn.editable.defaults.mode = 'inline';
			editable.editable();
            
        }
	
    };
})(jQuery);`

**Comment by bradmac** [comment]
:+1:

**Comment by ducdhm** [comment]
Well done @orazionelson 💯
