### ISSUE TITLE
[Feature] Integrating an image prototyping service in keditor

### ISSUE THREAD

**Issue by orazionelson** [Kademi/keditor#105]
In design It is useful to use image prototypes rather than real images, 
some services offer an easy way to build images on the fly.
Here I'll show how to integrate a service like: https://fakeimg.pl/

https://gist.github.com/orazionelson/f2cc4cc4055020ac5fd758b3a01d5417

**Comment by ducdhm** [comment]
Hi @orazionelson, it's great idea for creating prototype or wireframe. But with KEditor, we create/build real web content with real assets like images, videos, etc... I dont see any reason to add placeholder image to photo component. But if you want, you can your own component for it, somethings like `photoHolder`.

Cheers,
/Duc

**Comment by orazionelson** [comment]
hi @ducdhm,
let me say: keditor is simply great!!! And I'm usign it to build a tool to create page wireframes so I had the idea to integrate fakeimg.pl :)

I just found one problem in keditor, it makes a lot of entropy in the code, saving and saving the page makes a lot of empty sections.

So, I have to write a script to clean the result :\

**Comment by ducdhm** [comment]
@orazionelson I didn't get what you mean. Can you provide me example?

**Comment by orazionelson** [comment]
Hello,
I mean this, even if I create a simple container like this:
`<div data-type="container" data-preview="snippets/default/preview/row_12.png" data-keditor-title="Bootstrap container" data-keditor-categories="simple container">
    <div class="container">

    </div>
</div>`

the result is like this:
`<section>

<div class="row">
<div class="col-md-12" data-type="container-content">
<section><div class="container">

    </div></section><section data-type="component-text"></section>
</div>
</div>

</section>`

Another example, during the job on the page, you add and remove components and containers to see how it works, often the result is like this:
`            <div class="row">
              <div class="col-md-12" data-type="container-content">
                <div class="row">
                  <div class="col-md-12" data-type=
                  "container-content">
                    <div class="row">
                      <div class="col-md-12" data-type=
                      "container-content">
                        <div class="row">
                          <div class="col-md-12" data-type=
                          "container-content">...`

**Comment by ducdhm** [comment]
@orazionelson 

For first sample:
```
<section>
<div class="row">
<div class="col-md-12" data-type="container-content">
<section><div class="container">
</div></section>
<section data-type="component-text"></section>
</div></div></section>
```

The result is correct. Because you have a container with 1 column (`col-md-12`). Inside this container, you have a sub container (your custom container) and a blank text component.


```
<div class="row">
       <div class="col-md-12" data-type="container-content">
                <div class="row">`
                  <div class="col-md-12" data-type=
                  "container-content">
                    <div class="row">
                      <div class="col-md-12" data-type=
                      "container-content">
                        <div class="row">
                          <div class="col-md-12" data-type=
                          "container-content">...
```
If you can provide live example with step by step to reproduce, it's great. With only result like this, I can not help you.
