### ISSUE TITLE
How to change image in Kademi keditor container?

### ISSUE THREAD

**Issue by Newsourcing-A** [Kademi/keditor#108]
I have Image Component in my keditor. After dropping that Image Component into a Container, how can I change it with another image  from my computer?  In the Image Properties (which comes in right click) there is no option to upload  image  from my computer. Can only add image from urls from internet.

![capture](https://user-images.githubusercontent.com/18289063/39123775-7be10470-4716-11e8-833a-1b00d59e766e.PNG)

Please help me.
Thank you.

**Comment by ducdhm** [comment]
@Newsourcing-A: I think you're mentioning Text component. Not image component. About text component, we're using [CKEditor](https://ckeditor.com/ckeditor-4/). If you want to add more button like Upload, please read Documentation of CKEditor.

Cheers,
/Duc

**Comment by Newsourcing-A** [comment]
Hi,
   Thanks for your reply.  I mentioned the Image Component. After dropping that Image Component into a Container (marked by red arrow in the image), how can I change to another image from my computer? 

![imgcomp](https://user-images.githubusercontent.com/18289063/39170246-75c57696-47b8-11e8-81db-29c3ad02e630.PNG)

Please help.

**Comment by ducdhm** [comment]
@Newsourcing-A Is it in your own editor or live example of KEditor? Because at [example](https://rawgit.com/Kademi/keditor/master/examples/basic_with_blank_content.html) of KEditor, I still can change source of Image component. Just click `Change photo` button.

![newui](https://user-images.githubusercontent.com/1289631/39175489-a99c8e52-47d4-11e8-842e-9275694ce3e4.png)

**Comment by Newsourcing-A** [comment]
Hi,
Thanks a lot for your reply. For Image component I can upload photo. But for Image component with text, marked by red arrow in attached image I couldn't upload photo from my computer.

![capture](https://user-images.githubusercontent.com/18289063/39229258-972619cc-487f-11e8-9171-aece0cea9461.PNG)

 In the Image Properties (which comes on right click of image) there is no option to upload image from my computer. Can only add image from urls from internet.

![imgprop](https://user-images.githubusercontent.com/18289063/39229308-d7b87282-487f-11e8-9a6a-10a35c2c605c.PNG)

Please help me to upload photo from my computer for Image component with texts as shown in the first image. Thank you.

**Comment by ducdhm** [comment]
@Newsourcing-A As I mentioned above, it's CKEditor stuff. If you want to do something with it, please go to CKEditor forum or communities for helping.

Close this issue now.

Cheers,
/Duc
