### ISSUE TITLE
Text component toolbar ignores breaks?

### ISSUE THREAD

**Issue by voornaam** [Kademi/keditor#113]
I'm trying to create a custom toolbar but I can't figure out how to add breaks in it.  Is there a way to add breaks to the text component's toolbar? I've tried using '/' but this doesn't seem to work at all.

**Comment by ducdhm** [comment]
@voornaam Can you provide me the screenshot for what you want? I still dont get what you mean

**Comment by voornaam** [comment]
![screenshot_requested_toolbar](https://user-images.githubusercontent.com/39339299/40405818-619a3fd2-5e5e-11e8-8dad-15c0d3589aa1.PNG)
![screenshot_current_toolbar](https://user-images.githubusercontent.com/39339299/40405819-61c40862-5e5e-11e8-9cc9-33801b6a7c4b.PNG)

In these images you can see that one toolbar doesn't have any breaking spaces and the other does. The one with the breaking spaces is what I'm trying to accomplish but I haven't been successful thus far.

**Comment by ducdhm** [comment]
@voornaam Just take a look at [this file](https://github.com/Kademi/keditor/blob/master/src/less/keditor-component-text.less). Line 18 to 31, these lines is custom style of KEditor to force CKEditor toolbar items are in same row. You can remove these lines and you can see what you need.

Cheers,
/Duc
