### ISSUE TITLE
Toolbar for Youtube Settings not showing upon hover on IE11

### ISSUE THREAD

**Issue by reshiin** [Kademi/keditor#115]
Unable to change the video of youtube and vimeo because of this.

**Comment by reshiin** [comment]
also in google map

**Comment by ducdhm** [comment]
@anhnt can you help me on this? It's issue related to iframe z-index in IE11

**Comment by ducdhm** [comment]
Solution:
 * Default `z-index` of iframe is `-1`. A cover for iframe will be added and showed on top.
 * When double-click on cover of iframe (new element), cover will be hidden and `z-index` of iframe will be changed to `0`

New UI:
![New UI](https://user-images.githubusercontent.com/1289631/48758631-484c1380-ecd3-11e8-82d2-7a9820efa221.png)
