### ISSUE TITLE
component suggestion

### ISSUE THREAD

**Issue by remcovog** [Kademi/keditor#116]
Is there a place where people can download (or add) more components / containers, and submit to the project or community. I know, it is quit easy adding more components myself.  I can manage adding -for example- a pricetable or button component with configurable options, (I guess more people would be interested in these kinds of basic components). Or nice addons like a rgba colorpicker for background color....  
But I would really like to see some examples like tabs or arcordion, but that is out of my JS comfortzone to create...

**Comment by bradmac** [comment]
> Is there a place where people can download (or add) more components / containers, and submit to the project or community.

:+1:

**Comment by ducdhm** [comment]
Move to https://github.com/Kademi/keditor/issues/116
