### ISSUE TITLE
snippet with combined components

### ISSUE THREAD

**Issue by ivantowers** [Kademi/keditor#120]
Hello all,

I'm trying to replace the components that come with image and text, but, I want the image not to be modified with ckeditor, but instead be really the image component.

I created a snippet with image component then under that snippet i add a text component, text is show, but cant edit text.

Then try to create a container and add the code for the components, but also dont work.

I dont know if im doing something wrong or this is possible to do. 

Thank you in advance!!

**Comment by ducdhm** [comment]
@ivantowers You can create a snippet with `type` is `container`. In this container, you can add `image` component for your image and `text` component for your text. Example:

```
<div data-type="container" data-preview="path/to/preview/file" data-keditor-title="My container with image and text" data-keditor-categories="1 column">
    <div class="row">
        <div class="col-sm-12" data-type="container-content">
            <section data-type="component-photo">
                <div class="photo-panel">
                    <img src="snippets/img/somewhere_bangladesh.jpg" width="100%" height="" />
                </div>
            </section>
            <section data-type="component-text">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro labore architecto fuga tempore omnis aliquid, rerum numquam deleniti ipsam earum velit aliquam deserunt, molestiae officiis mollitia accusantium suscipit fugiat esse magnam eaque cumque, iste corrupti magni? Illo dicta saepe, maiores fugit aliquid consequuntur aut, rem ex iusto dolorem molestias obcaecati eveniet vel voluptatibus recusandae illum, voluptatem! Odit est possimus nesciunt.</p>
            </section>
        </div>
    </div>
</div>
```
