### ISSUE TITLE
Gen2 - plus buttons should not affect layout

### ISSUE THREAD

**Issue by bradmac** [Kademi/keditor#121]
Currently the G2 editor shows plus buttons where content can be added, which is great.

But the problem is that these buttons insert space in the content, so the editor doesnt show the page as it will actually look.

Instead, the plus buttons should be sitting above the content, ideally half over the first container and half over the second

Current layout:
![image](https://user-images.githubusercontent.com/826458/42139220-9ad8d760-7ddd-11e8-8878-4da3f64a9c41.png)

**Comment by stephen-fueldesign** [comment]
Here's an example from Duda's content editor to help further reinforce Brad's comment:

![ss-1](https://user-images.githubusercontent.com/39784677/42139284-ff104a00-7dde-11e8-9b8a-cbb543d12941.png)

![ss-2](https://user-images.githubusercontent.com/39784677/42139285-ff39f418-7dde-11e8-91e0-1d95ffd2fa8a.png)

![ss-3](https://user-images.githubusercontent.com/39784677/42139286-ff629508-7dde-11e8-83e0-950f0271b3d7.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/42139364-47f99806-7de0-11e8-84ee-78ec3097eaf4.png)
