### ISSUE TITLE
Gen2: Container column breakpoint controlls

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/keditor#123]
An awesome enhancement to Gen2 would be to have the ability to set and adjust container columns per breakpoints: Small, Medium, Large.

Bootstrap 3 has col-xs col-sm col-md col-lg (and bootstrap 4 has a 5th, col-xl).

The default view could be Large, and all default container settings could be col-lg.
Large screens - 4 column:
```
<div class="col-lg-3">
<div class="col-lg-3">
<div class="col-lg-3">
<div class="col-lg-3">
```

A selection mechanism (Small, Medium, Large) should turn the whole KEditor canvas to the max width of Small or Medium, simulating these breakpoints screen sizes. Extra small would not be required as these will just be full width.
![selection](https://user-images.githubusercontent.com/39784677/42663249-e763ce92-8688-11e8-9fe4-e7ff0314d20d.png)

Medium screen (3 column):
```
<div class="col-md-4 col-lg-3">
<div class="col-md-4 col-lg-3">
<div class="col-md-4 col-lg-3">
<div class="col-md-4 col-lg-3">
```

Small screen (2 column):
```
<div class="col-sm-6 col-md-4 col-lg-3">
<div class="col-sm-6 col-md-4 col-lg-3">
<div class="col-sm-6 col-md-4 col-lg-3">
<div class="col-sm-6 col-md-4 col-lg-3">

```

This would allow front end content authors better control of their content without the knowledge of bootstrap and Bootraps classes to manually adjust container column breakpoints - AND it has the added benefit and being able to visually see the screen size and how the content appears in that screen size mode.

**Comment by bradmac** [comment]
:+1: 

Awesome, this would solve a key problem which is the ability to control column layout for different breakpoints. Eg often we want col-lg-3 for a 4 col layout on desktop, but we want col-md-6 for smaller screens. Currently the user has to edit the html to do that.

**Comment by stephen-fueldesign** [comment]
Here are some screenshots from Duda, showing the interface in Small / Medium / Large modes.

**Small**
![small](https://user-images.githubusercontent.com/39784677/42665119-3db2fe04-8692-11e8-99ca-4843031941f8.png)

**Medium**
![medium](https://user-images.githubusercontent.com/39784677/42665125-44b4a766-8692-11e8-84b7-f2e7e3cb6239.png)

**Large (default, whatever size your screen is)**
![large](https://user-images.githubusercontent.com/39784677/42665173-80088008-8692-11e8-98ae-dbd2bf80f823.png)

**Comment by bradmac** [comment]
@remcovog thanks! @ducdhm what do you think?

**Comment by ducdhm** [comment]
New option:
![newOption](https://user-images.githubusercontent.com/1289631/61787174-74f39480-ae39-11e9-9dfd-ffec18804961.png)

New UI:
![newUI](https://user-images.githubusercontent.com/1289631/61787196-7d4bcf80-ae39-11e9-99d5-83934dfbab10.png)
