### ISSUE TITLE
k-editor gen2 "onContentChanged" bug

### ISSUE THREAD

**Issue by markyl0ts** [Kademi/keditor#124]
Im trying to use K-Editor event onContentChange which is defined:
` * @option {Function} onContentChanged Callback will be called when content is changed. Includes add, delete, duplicate container or component. Or content of a component is changed`

```
var contentHolder = $("textarea#contentArea");
contentHolder.keditor({
                onContentChanged: function (event, contentArea) {
                    contentHolder.text(contentHolder.keditor('getContent'));
                }
            });
```

onContentChange event only fires when i edited the content inside the component and delete component but wont work when I add container and component. I thought it would fire anytime their is an event in the editor.

Goal:
I'm trying to add the keditor value to a hidden field each time I edited some of its content.

**Comment by markyl0ts** [comment]
I was able to execute my goal by using this.

![image](https://user-images.githubusercontent.com/20597722/42940448-1334ec7e-8b8c-11e8-90b0-d89eb63a1516.png)

**Comment by ducdhm** [comment]
Fixed!
