### ISSUE TITLE
Dynamic content attributes

### ISSUE THREAD

**Issue by fusionconsulting** [Kademi/keditor#125]
Really like this component, just a question regarding the dynamic attributes:

It says the attributes will be converted to camel case but it seems they are not, for example I have:

```
<div data-type="component-planner" data-preview="/images/keditor/planner.png" data-keditor-title="Planner" data-planner-type="week">
    <div class="planner-container" data-dynamic-href="/planner/content"></div>
</div>

```
This should result in the URL being:

/planner/content?plannerType=week

But what I'm seeing is:

/planner/content?data-planner-type=week

Is there something else I need to do to process the attributes? 

Also, if I change the attributes from a settings panel, can I reload the panel with the new attributes?

Thanks

**Comment by bradmac** [comment]
> It says the attributes will be converted to camel case but it seems they are not, for example I have:

Sorry, that must be a mistake in the docs. In our implementation the attributes are converted to camel case in server side processing (ie template rendering) but thats outside of keditor's scope.

The ajax requests send the data param in its orginal form, as you saw.

> Also, if I change the attributes from a settings panel, can I reload the panel with the new attributes?

The settings panel is completely controlled by the component controller js. So you can reload the panel as long as your js handlers work with that.

**Comment by bradmac** [comment]
BTW, here's an example..
Component template
https://github.com/Kademi/kademi-dev/blob/master/src/main/marketplace/libs/rewardstore-lib/common/theme/apps/rewardstore/productListComponent.html

Settings controller js
https://github.com/Kademi/kademi-dev/blob/master/src/main/marketplace/libs/rewardstore-lib/common/theme/apps/rewardstore/productListComponent.js

Settings panel:
https://github.com/Kademi/kademi-dev/blob/master/src/main/marketplace/libs/rewardstore-lib/common/theme/apps/rewardstore/productListSettings.html

And you can peruse our collection of implementations here:
https://github.com/Kademi/kademi-dev/tree/master/src/main/marketplace

**Comment by fusionconsulting** [comment]
Hi, thanks for the clarification. The docs show the attributes being converted to camel case here:

https://github.com/Kademi/keditor#dynamic-content

Thanks for the links, I think initDynamicContent is what I've been looking for!
