### ISSUE TITLE
Spelling error in delete this component alert

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/keditor#127]
The alert when you delete a component contains a spelling error. It says "This action can not be undo!". But it should say, "This action cannot be undone!".

<img width="478" alt="screen shot 2018-08-22 at 1 20 08 pm" src="https://user-images.githubusercontent.com/41346338/44438051-7d33c600-a611-11e8-9e0d-4e212f47cb95.png">

**Comment by bradmac** [comment]
:+1:
