### ISSUE TITLE
Cannot read property 'draggable' of undefined

### ISSUE THREAD

**Issue by TheWhykiki** [Kademi/keditor#130]
Hello,

I try to implement the Pagebuilder in my page and want to save the results in a new textarea.
Everything is working fine, but when I try to set KEditors Content via $('.keditor-content-area').keditor('setContent',currentContent) I get the following error:

"Uncaught TypeError: Cannot read property 'draggable' of undefined"

![image](https://user-images.githubusercontent.com/12602174/46338024-55cc1200-c62f-11e8-960c-839b98370291.png)

This causes the problem that prevent default is not working anymore and instead of saving my layout, the saving task from my cms is triggered.

Can you help me out?

Thank you very much

**Comment by TheWhykiki** [comment]
Lines 1794 - 1797 are causing the error, if I comment them out its working....

        if (options.nestedContainerEnabled) {
            self.containerSnippets.draggable('option', 'connectToSortable', self.getConnectedForContainerSnippets());
        }
        self.componentSnippets.draggable('option', 'connectToSortable', body.find('.keditor-container-content'));

It seems draggable stays undefined.

**Comment by ducdhm** [comment]
@TheWhykiki which version of KEditor are you using?

**Comment by TheWhykiki** [comment]
Hey I'm using Version 1.1.6

I built a simple Joomla Pagebuilkder from your script and added slider features and so on. Very nice tool you made.
But it took me days to implement a slider as a container :-)

**Comment by ducdhm** [comment]
@TheWhykiki Thanks for using KEditor. I want to know more details about your issue. So can you give me the configuration of your KEditor?

**Comment by TheWhykiki** [comment]
I attached the two files I modified for my use....I hope this is what you need?!
M;aybe, if you are interested I can make a repository for my "pagebuilder" based on your KEditor and add you if possible.
So you can see the complete project...

I try to build a Pagebuilder who integrates in Joomla without touching the core.

**Comment by ducdhm** [comment]
@TheWhykiki maybe you missed the attachment? I dont see any attachments yet :)

**Comment by TheWhykiki** [comment]
Sorry Mister, I didn't see that js Files as attachement are not allowed. I made a rep from my files...

https://github.com/TheWhykiki/WhykikiPagebuilder/blob/master/plugins/system/whykikipagebuilder/assets/plugins/keditor.js

https://github.com/TheWhykiki/WhykikiPagebuilder/blob/master/plugins/system/whykikipagebuilder/assets/plugins/keditor-components.js

**Comment by ducdhm** [comment]
Hi @TheWhykiki, seem like you over-write code directly in source of KEditor. I thought you'll use keditor with PageBuilder is wrapper. In this case, can you check origin KEditor code first? If it has `Cannot read property 'draggable' of undefined` issue, please show me step by step to reproduct. If it doesnt, seem like your customize is wrong.

/Duc

**Comment by ducdhm** [comment]
Close now. Will re-open when reporter comes back.
