### ISSUE TITLE
Connection with innovastudio content builder

### ISSUE THREAD

**Issue by johnbatters** [Kademi/keditor#134]
Hi there, I was just wondering if I could get an idea on the connection between this project and the Innovastudio content builder (https://innovastudio.com/builderdemo/example1.html). We currently have theirs installed but I like some of the features on this project and would just like to know a little about the background and why they're so similar before I switch. Thanks

**Comment by johnbatters** [comment]
Hi Duc, thanks for getting back so quickly. Yes I definitely prefer what I've seen in your project, but I'm more curious about the history of the project. I'd just like to understand everything before committing to making the switch. Was it taken from the same code-base or were the similarities coincidental or was it loosely based on the same thing or...

Thanks

**Comment by ducdhm** [comment]
> Was it taken from the same code-base or were the similarities coincidental or was it loosely based on the same thing or...
@johnbatters You can check the commits to know the original code of KEditor. Honestly, KEditor and CB just have same sidebar style with toggle button (but in Gen 2, we remove it completely). So, KEditor and CB are different.

**Comment by johnbatters** [comment]
OK cool thanks. Was just curious. Am mid way through switching right now.
