### ISSUE TITLE
ASP MVC 

### ISSUE THREAD

**Issue by papyr** [Kademi/keditor#136]
Hi can you please include some infor mation on integrating with ASP MVC or a sample

**Comment by papyr** [comment]
https://github.com/Alaeddinalhamoud/ckeditor-MVC

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwi2yL2SlureAhWhVN8KHTwNDQsQFjAAegQIBxAB&url=https%3A%2F%2Fckeditor.com%2Fblog%2FCKEditor-for-ASP.NET-3.6.2-Released%2F&usg=AOvVaw0Hwg1034qTU-wgzq6aC0JC

**Comment by sepehr09** [comment]
dude! 
**CKeditor** is a  WYSIWYG HTML editor!
**KEditor** is a jQuery plugin which provides a content editor with drag and drop snippets!

**Comment by papyr** [comment]
can you share the jquery calls/api to save and reload snippets. I can attach to the ASP server, I went through your doc/code and could not find the correct list or sequence of steps to do so.
