### ISSUE TITLE
OnSave to Server

### ISSUE THREAD

**Issue by papyr** [Kademi/keditor#139]
Hi, I wanted to create a seperate issue to understand and also help others in the community trying to integrate with other servers.

1. While searching through help, I saw the configuration with many onChange etc calls, however I was not able to figure which call supported the POST to the Server for the HTML created. https://github.com/Kademi/keditor#configuration. 
2. What would structure of the content being posted back look like, would it be a blob/string or mimetype content? - what function would I call to send the page to server?
3. Loading Dynamic content, I saw the [product ](https://github.com/Kademi/keditor#dynamic-content) list example, can you please share, how can I load use an icon and have it load a widget for that icon by GET from server, in the below example I am trying to let the user load a graph widget, but when i save it, I need to give it a unique Id. I dont know how to send/save to server and how to get a new dynamic unique ID for the widget

```
<div data-type="component-products" data-num-products='4' data-store="store1" data-category="c1">
    <div data-dynamic-href='/_components/ecommerce/productTopSalesBarChart'></div>
</div>
```

**Comment by ducdhm** [comment]
> 1. While searching through help, I saw the configuration with many onChange etc calls, however I was not able to figure which call supported the POST to the Server for the HTML created. https://github.com/Kademi/keditor#configuration.

`onChange` is just a callback which will be called when content is changed. It's not good idea to save whenever content is changed. There're a ton of AJAX requests will be called when you do that. 


> 2. What would structure of the content being posted back look like, would it be a blob/string or mimetype content? - what function would I call to send the page to server?

It depends what you want. You can send html string of content or create a blob and send it to server as a file

Btw, I strongly recommend you create a button to do save stuff. You can use `$('#keditor-id').keditor('getContent')` to get current content of KEditor and then send this content to server by using AJAX.

> 3. Loading Dynamic content, I saw the product list example, can you please share, how can I load use an icon and have it load a widget for that icon by GET from server, in the below example I am trying to let the user load a graph widget, but when i save it, I need to give it a unique Id. I dont know how to send/save to server and how to get a new dynamic unique ID for the widget

I don't get what you mean. But as I understand, you want to know the way dynamic component/content/element works in KEditor, right? So let me explain:
 * Dynamic component is component with dynamic content which is generated from server whenever you access.
 * Dynamic component has 2 parts of it:
    * Dynamic href: It's described in `data-dynamic-href` of element. It's href where content will be loaded from
    * Data properties: They're properties which will be added to `dynamic href` when loading content.
 * In editing mode (when using KEditor), dynamic component will be initialized automatically and its content will be loaded from `data-dynamic-href` with `data-*` attributes
 * In reading mode (in normal web page), there are 2 ways to load content of dynamic component:
   1. You can use server-side rendering
   2. You can use AJAX to load content. You can check the way how KEditor init dynamic component to do it at [here](https://github.com/Kademi/keditor/blob/master/src/js/keditor.js#L1646)

Regards,
/Duc

**Comment by papyr** [comment]
Here is my scenario, on the left side panel, I have icons of charts, widgets, etc. I need to let user drag the icon over and pull that widget over to the page "DIV/container", on the background its really loading form the server. 

You answered the loading from the server really well.

My question is how can I ensure a new unique div, everytime the icon href target everytime it drops the content from the server on by dashboard page/container/div.

Also I noticed a small bug, if you open the samples with tab and drag over the text editor it spans beyond the container in a wide screen monitor. Not sure if its a simple fix on ensuring the editor does not go past that.

**Comment by ducdhm** [comment]
Hi @papyr, I dont really get what you want. Can you explain it step by step?
