### ISSUE TITLE
wysiwyg independent

### ISSUE THREAD

**Issue by raku** [Kademi/keditor#140]
Hello,

Can you make it also compatible with summernote, tinymce or can you make it wysiwyg independent?

**Comment by ducdhm** [comment]
Hi @raku,
If you take a look at [source of Text component](https://github.com/Kademi/keditor/blob/master/src/js/keditor-component-text.js), it's using CKEditor. So if you want to use summernote or tinymce, please feel free fork and edit this file. It's Open Source project 😃

**Comment by raku** [comment]
I've tried with summernote, but no luck, it is getting initialized, but I can't edit the content.

**Comment by ducdhm** [comment]
Hi @raku,
I think maybe you forget `contenteditable=true` attribute for the editing element 😃 

/Duc

**Comment by raku** [comment]
I've did this:

`(function ($) {
    var KEditor = $.keditor;
    var flog = KEditor.log;

    //CKEDITOR.disableAutoInline = true;

    // Text component
    // ---------------------------------------------------------------------
    KEditor.components['text'] = {
        options: {
            toolbarGroups: [
                {name: 'document', groups: ['mode', 'document', 'doctools']},
                {name: 'editing', groups: ['find', 'selection', 'spellchecker', 'editing']},
                {name: 'forms', groups: ['forms']},
                {name: 'basicstyles', groups: ['basicstyles', 'cleanup']},
                {name: 'paragraph', groups: ['list', 'indent', 'blocks', 'align', 'bidi', 'paragraph']},
                {name: 'links', groups: ['links']},
                {name: 'insert', groups: ['insert']},
                '/',
                {name: 'clipboard', groups: ['clipboard', 'undo']},
                {name: 'styles', groups: ['styles']},
                {name: 'colors', groups: ['colors']},
                {name: 'tools', groups: ['tools']},
                {name: 'others', groups: ['others']},
            ],
            title: false,
            allowedContent: true, // DISABLES Advanced Content Filter. This is so templates with classes: allowed through
            bodyId: 'editor',
            templates_replaceContent: false,
            enterMode: 'P',
            forceEnterMode: true,
            format_tags: 'p;h1;h2;h3;h4;h5;h6',
            removePlugins: 'table,magicline,tabletools',
            removeButtons: 'Save,NewPage,Preview,Print,Templates,PasteText,PasteFromWord,Find,Replace,SelectAll,Scayt,Form,HiddenField,ImageButton,Button,Select,Textarea,TextField,Radio,Checkbox,Outdent,Indent,Blockquote,CreateDiv,Language,Table,HorizontalRule,Smiley,SpecialChar,PageBreak,Iframe,Styles,BGColor,Maximize,About,ShowBlocks,BidiLtr,BidiRtl,Flash,Image,Subscript,Superscript,Anchor',
            minimumChangeMilliseconds: 100
        },

        init: function (contentArea, container, component, keditor) {
            flog('init "text" component', component);

            var self = this;
            var options = keditor.options;

            var componentContent = component.children('.keditor-component-content');
            componentContent.prop('contenteditable', true);

            componentContent.on('input', function (e) {
                if (typeof options.onComponentChanged === 'function') {
                    options.onComponentChanged.call(contentArea, e, component);
                }

                if (typeof options.onContainerChanged === 'function') {
                    options.onContainerChanged.call(contentArea, e, container);
                }

                if (typeof options.onContentChanged === 'function') {
                    options.onContentChanged.call(contentArea, e);
                }
            });

            //var editor = componentContent.ckeditor(self.options).editor;
            //var editor = 
                    componentContent.summernote({
                disableDragAndDrop: true
              });//self.options);//.editor;
              componentContent.on('click', function (e){
                  componentContent.summernote('focus');
                  componentContent.summernote('destroy');
              });
              
            /*editor.on('instanceReady', function () {
                flog('CKEditor is ready', component);

                if (typeof options.onComponentReady === 'function') {
                    options.onComponentReady.call(contentArea, component, editor);
                }
            });*/
        },

        getContent: function (component, keditor) {
            flog('getContent "text" component', component);

            var componentContent = component.find('.keditor-component-content');
            var id = componentContent.attr('id');
            //var editor = CKEDITOR.instances[id];
            return $('#' + id).summernote('code');
            /*if (editor) {
                return editor.getData();
            } else {
                return componentContent.html();
            }*/
        },

        destroy: function (component, keditor) {
            flog('destroy "text" component', component);

            var id = component.find('.keditor-component-content').attr('id');
            $('#' + id).summernote('destroy');
        }
    };

})(jQuery);`

**Comment by ducdhm** [comment]
Hi @raku,
Do you have any live example for that?

**Comment by raku** [comment]
no

**Comment by ducdhm** [comment]
Hi @raku,
Btw, I see in your code, when clicking in componentContent, why you need to `focus` and `destroy` summernote? I think it's not right.

/Duc

**Comment by raku** [comment]
destroy was for a test, you can delete it, but the effect is same

**Comment by ducdhm** [comment]
@raku I really need a live example on JSFiddle or JSBin or something like that to help you. Without it, I cant.

/Duc

**Comment by mlandmann** [comment]
What file did you  make the toolbar modification in?  I can't seem to get my changes to take.  I want to radically change the toolbars and integrate in cffinder.  Has anyone done that?

**Comment by mlandmann** [comment]
The toolbar icons are all on one line.  If you want a large set of ICONS, a horizontal scroll is needed. How do you configure the toolbar icons to be on multiple lines?

**Comment by ducdhm** [comment]
@mlandmann It's just CSS stuff. You can inspect CKEditor elements and find out why it's not in multi-lines.

/Duc
