### ISSUE TITLE
CKEditor 5 integration?

### ISSUE THREAD

**Issue by Wewerica** [Kademi/keditor#145]
Hello,
have anyone tried updating CKEditor from version 4.5.6 to version 5?

Cheers

**Comment by bradmac** [comment]
No, but I'm keen to look into it sometime in the near future

**Comment by bradmac** [comment]
@ducdhm any thoughts?

**Comment by ducdhm** [comment]
New UI:
![newUI](https://user-images.githubusercontent.com/1289631/57665718-38c8da00-7627-11e9-8639-af82bd2cf96c.png)
