### ISSUE TITLE
How to console this $('#content-area').keditor('getContent'); whenever i add new item or remove to page ??

### ISSUE THREAD

**Issue by ErMandeep** [Kademi/keditor#150]
<script type="text/javascript">
    $(document).ready(function(){
        $("button").click(function(){
var fileContent = $('#content-area').keditor('getContent');
            $.ajax({
                type: 'POST',
                url: 'basic_with_content.php',
                data: {
                body: fileContent
                       },            
            dataType: 'json',
                success: function(data) {

                    console.log(data);
                }
            });
   });
});
</script>

**Comment by ducdhm** [comment]
@ErMandeep Can you explain me more what your case is?
