### ISSUE TITLE
image upload response as blob

### ISSUE THREAD

**Issue by RezaErfani67** [Kademi/keditor#153]
i save my uploaded files in shared folder...
the problem is here that chrome browser not allowed to load file from unc path...(because security reasons)...
what do you suggest for me?
can i should get it as blob and then show my uploaded image?

**Comment by ducdhm** [comment]
Hi @RezaErfani67, you need a host/server to upload/get image. If you want test your file in local, you can follow [this guide](https://cmatskas.com/interacting-with-local-data-files-using-chrome/) to enable access local file for Chrome.

/Duc
