### ISSUE TITLE
Gen 2: Support custom sidebar

### ISSUE THREAD

**Issue by ducdhm** [Kademi/keditor#154]
Sometimes, I want sidebar to show some extra settings.

**Comment by anhnt** [comment]
This has been done inside kademi. will push

**Comment by ducdhm** [comment]
@anhnt There were many changes in KEditor since we forked to Kademi. So I suggest I'll do it by check the diff in commits of Kademi

**Comment by ducdhm** [comment]
New option:
![new option](https://user-images.githubusercontent.com/1289631/59550067-9044c780-8f90-11e9-9e80-4cd6df7c0b18.png)

UI Example:
![new UI](https://user-images.githubusercontent.com/1289631/59550069-98046c00-8f90-11e9-8b16-6da039c6829c.png)
