### ISSUE TITLE
keditor-snippets-list not working 

### ISSUE THREAD

**Issue by Programmer-MahmoudAhmed** [Kademi/keditor#16]
keditor-snippets-list dont get any snippets from file snippets.html 
and only place i see this script working was in this link only 
http://www.jqueryscript.net/other/jQuery-Based-Content-Editor-and-Layout-Builder-KEditor.html

i love it when i see it working but can't  get it working please if there is any help

**Comment by anhnt** [comment]
Please test this under http server. that should work

**Comment by ducdhm** [comment]
@Programmer-MahmoudAhmed Hi, can you give me more information for checking?

**Comment by bradmac** [comment]
@ahnt I don't think it should need a running server. That's just for dynamic component evaluation

**Comment by Programmer-MahmoudAhmed** [comment]
there is no any html file working like the i posted  so im try to get the file on this site and im make every thing work Except snippets list Because \ snippetsUrl: 'snippets/default/snippets.html',
dos not get any thing and this photo for final work with me 
http://s30.postimg.org/e53qauopd/image.jpg

stile cant' get  snippets list showing

**Comment by Programmer-MahmoudAhmed** [comment]
@anhnt  im tested on http server when i know its not make any change 
any won can download the file from here and he will see its not working 
the only copy from this script working on the link i post it before

**Comment by ducdhm** [comment]
@Programmer-MahmoudAhmed You can download version 1.0.2 of KEditor at https://github.com/Kademi/keditor/releases/tag/1.0.2. It's same with example at http://www.jqueryscript.net/other/jQuery-Based-Content-Editor-and-Layout-Builder-KEditor.html

**Comment by ducdhm** [comment]
@Programmer-MahmoudAhmed As I checked in my local, seem like snippets list will be not loaded in Chrome but loaded in FF and IE. The reason chrome doesn't allow to loading snippets list is security reason. Please check solution at http://stackoverflow.com/questions/10752055/cross-origin-requests-are-only-supported-for-http-error-when-loading-a-local.

**Comment by Programmer-MahmoudAhmed** [comment]
@ducdhm  thanks alot i checked in fire fox and its work and i will check the link in stackoverflow to know how i can fixed in chrome

**Comment by madu12** [comment]
how to get full ckeditor

**Comment by bradmac** [comment]
Not sure what you mean? Are you looking for the ckeditor source code?

http://ckeditor.com/

**Comment by ducdhm** [comment]
@umarch06 You can see what you need at:
 * [Customize snippet](#customize-snippet)
 * [Customize component type](#customize-component-type)
 * [Dynamic content](#dynamic-content)

**Comment by bradmac** [comment]
:+1:

**Comment by umarch06** [comment]
but I cannot have a clear documentation for that. I tried to add the custom code in dynamic_content file. But nothing showd in the snippet and containers  tabs.

**Comment by bradmac** [comment]
The snippets are loaded from snippets.html by default. You can change that file, or change the config options to load from a different file using the snippetsUrl property:
```
@option {String} snippetsUrl Url to snippets file
```

**Comment by umarch06** [comment]
I added my custom snippet in snippet.html file and used same attributes for div. But I wonder why my custom added snippet not appearing in side bar  in that.

**Comment by bradmac** [comment]
Note that its loaded by ajax, so doing a page refresh will not cause it to be reloaded. I suggest you open the snippets url in your browser directly to confirm if your changes are being loaded.

**Comment by umarch06** [comment]
@bradmac I need to talk to you personally. I am stuck into a place as I have used this plugin very heavily and cannot replace it with anything else now.

**Comment by bradmac** [comment]
Sorry man, I'm a bit busy today! But its really easy, Kademi uses heaps of extra snippets, so it definitely works.

Just open up snippets.html in your browser and you will see. Most likely all you need to do is hard refresh the snippets file

**Comment by umarch06** [comment]
I did that too but not worked. Thanks for the time and hats off to you guys efforts.
I just needed to show you some keditor modified by me in a confidential website. please leave an email for me once you are free. I would be grateful.
regards,
umar

**Comment by umarch06** [comment]
@bradmac @ducdhm I have checked the snippet.html after adding my own simple line break (<br>) in snippet area. It  is being shown in snippet.html but not in tab after keditor loads

![image](https://cloud.githubusercontent.com/assets/13533390/22283055/d35920f4-e301-11e6-9d57-f4f03e512d71.png)

![image](https://cloud.githubusercontent.com/assets/13533390/22283067/e553b22e-e301-11e6-9428-642d38c4802a.png)

![image](https://cloud.githubusercontent.com/assets/13533390/22283080/ffab2b84-e301-11e6-9720-55c22d64842e.png)
