### ISSUE TITLE
$("#conent-area").keditor('setcontent', content); returns that the content area does not exsist but it does

### ISSUE THREAD

**Issue by DJ1TJOO** [Kademi/keditor#162]
$("#conent-area").keditor('setcontent', content); returns that the content area does not exsist but it does. Have I done something wrong?

**Comment by DJ1TJOO** [comment]
When I use this:  $('#content-area').keditor('setContent', '<?php if(isset($content)){echo $content;} ?>', $('#content-area')); It doesn't return an error and leaves blankscreen (php is from mysql database)

**Comment by ducdhm** [comment]
Hi @DJ1TJOO, let me explain you the structure of keditor:

```
keditor
|----content-area
     |----container
          |----component   
```

The second param should be content-area which you want to set content not the element which you initialize as keditor instance. In your example, the keditor element has `#content-area` id. It's is `keditor` in structure, not `content-area`

**Comment by DJ1TJOO** [comment]
Thanks a lot @ducdhm. I assigned the keditor on to my content-area I've changed it now to another div.
