### ISSUE TITLE
Images not showing after adding snippet

### ISSUE THREAD

**Issue by mehboobscore** [Kademi/keditor#163]
Whenever i tried to add the built in snippet with images i found that images are not loading i have hosted the demo at my local IIS windows 10. Any suggestions for me.

**Comment by ducdhm** [comment]
@mehboobscore can you give me the screenshot of Network tab in your browser?

**Comment by mehboobscore** [comment]
![Screenshot_12](https://user-images.githubusercontent.com/46346908/59696774-174ea580-9206-11e9-9087-98c3327f34b3.png)

**Comment by ducdhm** [comment]
@mehboobscore I mean all. I want to know why the image is not loaded. Not only for JS. Thanks.

**Comment by mehboobscore** [comment]
This image have all of the loaded network detail. Images are loading in network but not showing at page you can see in the image.
![Screenshot_13](https://user-images.githubusercontent.com/46346908/59701079-33eedb80-920e-11e9-84bb-6fdcbd3b5ad9.png)
![Screenshot_14](https://user-images.githubusercontent.com/46346908/59701169-6ac4f180-920e-11e9-955e-4a63d4b2299a.png)
![Screenshot_15](https://user-images.githubusercontent.com/46346908/59701175-6c8eb500-920e-11e9-83b1-765ca942fb5e.png)
![Screenshot_16](https://user-images.githubusercontent.com/46346908/59701221-88925680-920e-11e9-8b77-cc88749748fc.png)

**Comment by ducdhm** [comment]
@mehboobscore Thanks for your information. I have checked and seem like it related to CKEditor 5. It removes all image, div with class. Let me fix it.

**Comment by mehboobscore** [comment]
@ducdhm Thanks for help i will wait for your confirmation.

**Comment by ducdhm** [comment]
Let's move to [this issue](https://github.com/Kademi/keditor/issues/164). I found the root cause for it.
