### ISSUE TITLE
Revert to CKEditor 4

### ISSUE THREAD

**Issue by ducdhm** [Kademi/keditor#164]
After upgrading from `CKEditor 4` to `CKEditor 5` in a few months ago, some of `compontent-text` snippets for do not work as expected. The reason is `CKEditor 5` stripped all `class`, `id` and inline styles (more details at [here](https://github.com/ckeditor/ckeditor5/issues/592), [there](https://github.com/ckeditor/ckeditor5/issues/1178) and [over there](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#why-does-the-editor-filter-out-my-content-styles-classes-elements-where-is-configallowedcontent-true))

So, I decided to revert back to `CKEditor 4`

**Comment by mehboobscore** [comment]
Sure what i need to do let me know.

**Comment by ducdhm** [comment]
Works perfectly. Example: http://kademi.github.io/keditor/examples/basic_with_content.html

**Comment by Stiropor** [comment]
Hmm, aren't there `allowedContent`, `disallowedContent` and other settings in CK5 also, which would prevent stripping and removing attributes?

**Comment by ducdhm** [comment]
@Stiropor sorry but... no. CKEditor 5 is a diffrent thing. No `allowedContent` or `disallowedContent`. You need to implement your own plugin to handle all other things which are not included in standard plugins of Version 5 :(

**Comment by Stiropor** [comment]
@ducdhm Didn't know that, I did noticed it's a mess to upgrade with lots of things missing, I guess it's all about collaboration :( Thanks for reply and keep up the good work!

**Comment by mehboobscore** [comment]
I am facing this issue now please have a look on it:
![Screenshot_17](https://user-images.githubusercontent.com/46346908/59756252-cb9e0980-92a2-11e9-8c78-9876a18ee27f.png)

Thanks

**Comment by ducdhm** [comment]
@mehboobscore if you're working on current branch, it's under-structuring branch so sometimes the code is broken. Please check [releases](https://github.com/Kademi/keditor/releases) for stable version.

Btw, I have pushed the fix, you can check it now.

**Comment by mehboobscore** [comment]
@ducdhm Thanks
