### ISSUE TITLE
add carousel

### ISSUE THREAD

**Issue by srikanthmovva** [Kademi/keditor#169]
i need to add more components like carousel, navbar etc. could you please let me know how to edit the code and add new components.
Thank you!

**Comment by ducdhm** [comment]
@srikanthmovva We already have guideline in homepage of keditor
 * Firstly, you need add more snippets. Please read at [here](https://github.com/Kademi/keditor#customize-snippet)
 * Secondly, you need add JS stuff for your snippets. Please read at [here](https://github.com/Kademi/keditor#customize-component-type)
