### ISSUE TITLE
Edit or add new form builder

### ISSUE THREAD

**Issue by srikanthmovva** [Kademi/keditor#170]
I need to know how to edit the settings of an element in the form (lets say button settings).
Thank you

**Comment by ducdhm** [comment]
@srikanthmovva You can follow [this guide](https://github.com/Kademi/keditor#customize-component-type) for customize component. You can edit source code of existing components at [here](https://github.com/Kademi/keditor/tree/master/src/components)

**Comment by ducdhm** [comment]
@srikanthmovva you also can see FormBuilder docs for [custom element](https://formbuilder.online/docs/formBuilder/options/templates/)
