### ISSUE TITLE
iframeMode false option not working

### ISSUE THREAD

**Issue by cmohanraj10** [Kademi/keditor#171]
`$('#content-area').keditor({
	iframeMode: false
});`

I am using the above code for initializing the editor without iframe. Editor initialized but its within the iframe. Any Idea?

**Comment by ducdhm** [comment]
@cmohanraj10 Which version of KEditor are you using? If you're using version 2 (in master branch), it always use iframe. The reason: iframe is required for [this feature](https://github.com/Kademi/keditor/issues/156)
