### ISSUE TITLE
bug in Form component

### ISSUE THREAD

**Issue by srikanthmovva** [Kademi/keditor#173]
http://kademi.github.io/keditor/examples/settings_for_container.html

in the "settings for container" example, im trying to add a form but it is adding 2 forms at same time( as a single component)

**Comment by ducdhm** [comment]
@srikanthmovva can you give me more details? Which browser are you using?

**Comment by srikanthmovva** [comment]
ok. go to "settings for container" example and add a form. you will understand what i meant- multiple forms are added when we try to add only just one form. and if i add a button in the form, edit, delete copy buttons are not working

**Comment by ducdhm** [comment]
@srikanthmovva I can see edit, delete or copy buttons are not working but I still see only 1 form added. Can you give me screenshot?

**Comment by srikanthmovva** [comment]
![keditorformbug](https://user-images.githubusercontent.com/41923272/60251010-5b683700-98e5-11e9-9139-34a99eaa5f9b.PNG)

**Comment by srikanthmovva** [comment]
@ducdhm take a look at the screenshot and i think in all the examples it is the same.

**Comment by srikanthmovva** [comment]
this 2 forms error is raised only when it is added directly with out a container. if you add a container first and then add the form builder component then it is adding single form.
but however the edit,copy,delete buttons are throwing jquery errors in the console.

**Comment by ducdhm** [comment]
@srikanthmovva The issue here is formBuilder is initializing inside iframe. I'm changing the way to edit form.

**Comment by ducdhm** [comment]
New UI:
1. Design button
![newUI1](https://user-images.githubusercontent.com/1289631/60431526-35ff6400-9c2a-11e9-8d01-51b1e30bc5f9.png)

2. Modal for designing form
![new UI2](https://user-images.githubusercontent.com/1289631/60431540-3b5cae80-9c2a-11e9-9efc-e015a54ca0ad.png)

**Comment by ducdhm** [comment]
@srikanthmovva Can you check it again?

**Comment by srikanthmovva** [comment]
![image](https://user-images.githubusercontent.com/41923272/60431788-3bef4800-9c1e-11e9-83cd-7646d176da43.png)
the circled one is " i added a container and then added a form". and the bottom one is " i added a form directly".
both cases are not working-but if u see when i added a form directly "No form content" is displayed twice( just as previously it is adding 2 forms nested)

**Comment by ducdhm** [comment]
@srikanthmovva You added form inside new container or below new container?

**Comment by srikanthmovva** [comment]
top red circled one is " form in a container"

bottom i added a form directly which gave me "No form container " twice.

**Comment by srikanthmovva** [comment]
![image](https://user-images.githubusercontent.com/41923272/60432183-41995d80-9c1f-11e9-9f93-724ff8037812.png)
 in this picture i added a container and then added a form inside it.

**Comment by srikanthmovva** [comment]
![image](https://user-images.githubusercontent.com/41923272/60432298-891fe980-9c1f-11e9-863f-e11ba60b50c6.png)
in this picture i added a form directly without adding any container. as you can see it is adding multiple "No form content"

**Comment by srikanthmovva** [comment]
if you are not seeing the second error, refresh the page (without saving anything, so that it will give you empty page again) and add a form directly without a container.

**Comment by ducdhm** [comment]
@srikanthmovva Fixed!

**Comment by srikanthmovva** [comment]
i still see it the same. no change :/

**Comment by ducdhm** [comment]
You need to clear cache to see the change!

**Comment by srikanthmovva** [comment]
i did cleared the cache. but still not working. i also tried from another computer(just to make sure no js is saved in cache) but still didnt worked. (i used google chrome in windows and also in mac)

**Comment by srikanthmovva** [comment]
it did changed something.but didnt solve the issue. because when i add a container and a form inside the container i see nothing added. when i add a form directly without a container then im seeing"no form content" once (previously multiple ).
(i checked in safari too)

**Comment by srikanthmovva** [comment]
<img width="1677" alt="Screen Shot 2019-07-01 at 5 19 18 PM" src="https://user-images.githubusercontent.com/41923272/60434399-b0c58080-9c24-11e9-83ea-6565d132122b.png">
this is the latest screenshot of " adding a form inside a container"
-used safari in Mac

**Comment by srikanthmovva** [comment]
<img width="1677" alt="Screen Shot 2019-07-01 at 5 19 52 PM" src="https://user-images.githubusercontent.com/41923272/60434477-d6eb2080-9c24-11e9-8300-6b09a9466518.png">
this is the latest screenshot of " adding a form directly(outside the container)" 
-used safari in Mac

**Comment by ducdhm** [comment]
@srikanthmovva I have pushed the fix. Hope it work well!

**Comment by srikanthmovva** [comment]
@ducdhm now it it working fine. but when you build a form and click save, it is raising js error as below:
form-render.min.js:6 Uncaught TypeError: t.emptyContainer is not a function
    at t.render (form-render.min.js:6)
    at HTMLFormElement.<anonymous> (form-render.min.js:6)
    at Function.each (jquery-1.11.3.min.js:2)
    at m.fn.init.each (jquery-1.11.3.min.js:2)
    at m.fn.init.t.fn.formRender (form-render.min.js:6)
    at Object.renderForm (keditor-component-form.js?714a:10)
    at HTMLButtonElement.eval (keditor-component-form.js?714a:75)
    at HTMLButtonElement.dispatch (jquery-1.11.3.min.js:4)
    at HTMLButtonElement.r.handle (jquery-1.11.3.min.js:4)

**Comment by ducdhm** [comment]
@srikanthmovva The issue occurs when form is empty. I have fixed this issue as well as. Hope it's latest version for this component xD

**Comment by srikanthmovva** [comment]
now it is working fine when a form is added inside a container. but if you try to add a form outside a container and edit it and click save, it is giving the same error :(

**Comment by srikanthmovva** [comment]
@ducdhm sorry. issue is not with the container. 
if you add a second form in the same page then it is raising the error when saving the second form

**Comment by srikanthmovva** [comment]
@ducdhm try adding 2 forms in 2 different containers.

**Comment by ducdhm** [comment]
@srikanthmovva Can you try again :D

**Comment by srikanthmovva** [comment]
i tried it(after clearing the cache). it is still same :/

**Comment by srikanthmovva** [comment]
<img width="1677" alt="Screen Shot 2019-07-02 at 2 17 11 PM" src="https://user-images.githubusercontent.com/41923272/60498795-df029900-9cd4-11e9-851d-2d702cf1a7fe.png">
<img width="1677" alt="Screen Shot 2019-07-02 at 2 17 45 PM" src="https://user-images.githubusercontent.com/41923272/60498796-df9b2f80-9cd4-11e9-91b9-eacc782ef14c.png">
try adding forms in same container, different container, outside container

**Comment by srikanthmovva** [comment]
@ducdhm im trying all the possible ways to add multiple forms. there are 2 possible ways to get errors.
1. if you add a form in **sub container** error is raised. (more than one for in a page)
2. if you add a form after you click **save**, error is raised.
this might help you in solving the issue :)

**Comment by ducdhm** [comment]
@srikanthmovva please check again

**Comment by ducdhm** [comment]
Fixed!

**Comment by srikanthmovva** [comment]
working fine :D
