### ISSUE TITLE
Text Editor in subcontainer

### ISSUE THREAD

**Issue by srikanthmovva** [Kademi/keditor#175]
i tried adding text in a subcontainer and edit it. but the text editor is somewhere down.
![image](https://user-images.githubusercontent.com/41923272/60255942-493ec680-98ee-11e9-8d3c-490153cda64d.png)

**Comment by srikanthmovva** [comment]
add a image and after that add some text in a container down to it (container/subcontainer)

**Comment by ducdhm** [comment]
@srikanthmovva Seem it's css issue when editable-content inside iframe. Let me check!

**Comment by srikanthmovva** [comment]
@ducdhm yep. and please do check for thumbnails, articles also. it is same issue.

**Comment by ducdhm** [comment]
@srikanthmovva Sure, they's using CKEditor so they have same issue.

**Comment by ducdhm** [comment]
@srikanthmovva fixed!

**Comment by srikanthmovva** [comment]
it is solved but there is a lot of "shaking" while using the ckeditor :( i can hardly use it :/

**Comment by srikanthmovva** [comment]
@ducdhm 
![image](https://user-images.githubusercontent.com/41923272/60559476-1a9b7280-9d6a-11e9-88b1-87744d00ef91.png)
![image](https://user-images.githubusercontent.com/41923272/60559707-f2f8da00-9d6a-11e9-86db-337bbd748487.png)
if you see both the images, when the cursor is moved inside the container, some extra space is added to it. if we place the cursor on the editor, the container is expanding and contracting continuously because the editor is on the bottom line of container. if you could move the editor little upside it might fix the problem.
Thank you :)

**Comment by ducdhm** [comment]
New UI:
![newUI](https://user-images.githubusercontent.com/1289631/60645643-6c73f380-9e63-11e9-98ee-9bb0ca4c52b1.png)

**Comment by ducdhm** [comment]
@srikanthmovva I have update UI for keditor. Please check!

**Comment by srikanthmovva** [comment]
@ducdhm ok i will check and let you know. please try to fix the bug in form too if possible. 
Thank you

**Comment by ducdhm** [comment]
@srikanthmovva This issue for text editor. Please dont involve other issue

**Comment by srikanthmovva** [comment]
@ducdhm hey everything is working fine.
but i'm not sure if it is a bug or no. i selected few words in a paragraph and tried changing it to heading1. but the whole paragraph is changed to heading1.

**Comment by ducdhm** [comment]
@srikanthmovva It's CKEditor issue or stuff. Not KEditor :)

**Comment by srikanthmovva** [comment]
ok cool :D
