### ISSUE TITLE
Bug in Dynamic Content Component

### ISSUE THREAD

**Issue by srikanthmovva** [Kademi/keditor#176]
snippets/_dynamic_content.html?data-website=website01&data-blog=blog01&data-article=article01&data-tags=tag01%2Ctag02:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by ducdhm** [comment]
I don't why `_dynamic_content.html` is not loaded in github.io. Just changed to `dynamic_content.html` and it works
