### ISSUE TITLE
Snippet toolbar is overlapping content

### ISSUE THREAD

**Issue by anhnt** [Kademi/keditor#18]
![overlapping](https://cloud.githubusercontent.com/assets/735555/14416397/f52d1c10-ffd3-11e5-9c91-742e44c7ef2a.PNG)

**Comment by ducdhm** [comment]
@anhnt It's just styling. It's default style of Keditor. You can style for your content like
```css
body.opened-keditor-sidebar .your-content-selector {
   // Style when keditor sidebar is opened
}
```

**Comment by anhnt** [comment]
thanks so much! that works for me :)
