### ISSUE TITLE
[Feature request] Hide the setting panel when component loses focus to a new component.

### ISSUE THREAD

**Issue by manuongithub** [Kademi/keditor#180]
**Functionality**
When the currently selected component loses focus and a new component is selected, do the following:

1) Hide the settings panel of the previously selected component
2) newly selected component has settings then open settings panel of the newly selected component else don't show any settings panel...

**Comment by ducdhm** [comment]
Done!

Thank @manuongithub for your suggestion 💯

**Comment by manuongithub** [comment]
thanks, we should also hide the settings panel when preview is switched on

**Comment by ducdhm** [comment]
@manuongithub I already did it in https://github.com/Kademi/keditor/issues/196
