### ISSUE TITLE
[BUG] duplicate component button click is broken

### ISSUE THREAD

**Issue by manuongithub** [Kademi/keditor#181]
**Describe the bug**
the duplicate component button click is broken
when i click the icon to duplicate component, it does nothing... reproducible in the demo on this site too...

**Comment by ducdhm** [comment]
@manuongithub cause [this issue](https://github.com/Kademi/keditor/issues/158) so no duplicate anymore. It's Copy button but this feature is under-structure. So won't fix.

You're working in development branch of KEditor. If you want a stable version, please check Release
