### ISSUE TITLE
Keditor should have option handler function to process when adding a component without a any existing container

### ISSUE THREAD

**Issue by anhnt** [Kademi/keditor#185]
![image](https://user-images.githubusercontent.com/735555/61288537-857c8d00-a7f1-11e9-99e3-a2780f329338.png)

When adding a component to content area which has no existing container, Keditor should have option function that allow hooking into it to append any custom html that wraps the component. We need that for current Kademi EDM editor and content editor which have different container structures

**Comment by ducdhm** [comment]
@anhnt do you mean [this option](https://github.com/Kademi/keditor/blob/master/src/keditor/constants/defaults.js#L15)?
