### ISSUE TITLE
[BUG] Bootstrap 4 Column Resize

### ISSUE THREAD

**Issue by hitaloramon** [Kademi/keditor#192]
Description:
I know keditor is based on bootstrap 3, but I use bootstrap 4 and everything works perfectly except the column resizing part. It simply doesn't change column values, because dragging the column doesn't work when I'm using bootstrap 4 CSS. Any idea what it is? No console shows no errors

Gif Demo: https://i.imgur.com/xKHbfUx.gifv

Version:
Last commit

Sorry for english using google translator

**Comment by ducdhm** [comment]
@hitaloramon Can you provide me a live example/code for this issue?

**Comment by hitaloramon** [comment]
@ducdhm  I made two examples, what changes is just a version of bootstrap 

Live Exemplo: https://www.cmsgeek.m7web.com.br/index.html

**Comment by ducdhm** [comment]
Fixed!

**Comment by ducdhm** [comment]
@hitaloramon Please kindly check the latest code

**Comment by hitaloramon** [comment]
thanks @ducdhm 

what about it?
>taking advantage of the post, in the keditor examples, when copying and pasting a component that has text, ckeditor does not work on the element that was pasted. Are you aware of this problem?

**Comment by ducdhm** [comment]
@hitaloramon can you create other issue for it? I'll fix it in other issue 😄

**Comment by hitaloramon** [comment]
@ducdhm I noticed that the bug was only corrected in desktop view, when selecting, for example, Mobile, Tablet and Laptop the problem continues.

**Comment by hitaloramon** [comment]
I realized that another problem happens. When resizing the Desktop view column and trying, for example, to resize the same column in Laptop or any other view, the bug happens again and cannot be resized. You can test again in my bootstrap 4 example
