### ISSUE TITLE
[BUG] CKeditor Does Not Appear in Copied Text Components

### ISSUE THREAD

**Issue by hitaloramon** [Kademi/keditor#193]
Description:
By copying any text component and pasting it into another area, you will no longer be able to edit content with ckeditor. The ckeditor bar is not visible.

Version:
Last Commit

Reproduce:
1 - Add some text component
2 - Click on the copy button
3 - Paste in another area
4 - Try to edit the text

Expected behavior
Being able to edit text with ckeditor

**Comment by ducdhm** [comment]
Fixed!

**Comment by hitaloramon** [comment]
@ducdhm solved the problem of this!

NOTE: 'I commented another bug in my previous issue.'
