### ISSUE TITLE
[BUG] Bootstrap 4 Column Resize

### ISSUE THREAD

**Issue by hitaloramon** [Kademi/keditor#194]
Description:
The previous bug reported has been fixed in part. I realized that when resizing a column in Desktop view and then switching to Laptop, tablet or mobile view, the same column can no longer be resized, but the others work normally. Using the bootstrap 3 example this does not occur.

How to reproduce the problem:
1 - Resize a column in Desktop View
2 - Switch to Laptop View
3 - Try resizing the same previous column

Live Example: https://www.cmsgeek.m7web.com.br/bootstrap4.html

**Comment by hitaloramon** [comment]
Any news on this? @ducdhm

**Comment by ducdhm** [comment]
@hitaloramon The main issue here is styles of BS4. I'm investigating...

**Comment by hitaloramon** [comment]
@ducdhm, I think find out why this problem happens. The bootstrap 4 grid system has an additional class prefix, which is col-xl for desktop, and when resizing it changes in a lower view. So I tried changing the device constants to:

const DEVICE_MODE = {
     MOBILE: 'sm',
     TABLET: 'md',
     LAPTOP: 'lg',
     DESKTOP: 'xl',
};

and it seems that solved the problem.

**Comment by ducdhm** [comment]
@hitaloramon I think the `DEVICE_MODE` need to be configurable. Let me update it in keditor

**Comment by ducdhm** [comment]
New options:
![image](https://user-images.githubusercontent.com/1289631/62794628-c28d2400-bafe-11e9-9413-1e5ffe3f99da.png)
