### ISSUE TITLE
[Feature request] is it possible to drag n drop the components while adding them to the page

### ISSUE THREAD

**Issue by manuongithub** [Kademi/keditor#197]
**Functionality**
is it possible to drag n drop the components while adding them to the page? In previous versions of keditor we used to have this feature. The components were visible in the sidebar and we used to drag n drop them on the builder....?

**Comment by ducdhm** [comment]
Hi @manuongithub, in version 2, we decided to use "Add" button for adding content. If you want to use drag n drop snippets from sidebar to content-area, you can use version 1 KEditor at [here](https://github.com/Kademi/keditor/tree/keditor-v1).

/Duc

**Comment by manuongithub** [comment]
is there a commit in version 1 or version 2 that I should look at for guidance when trying to add the functionality back to version 2's code for my own implementation..?

**Comment by ducdhm** [comment]
@manuongithub honestly, I think it's impossible. Version 1 is in only 1 file but in version 2, I applied webpack for KEditor so I splitted keditor into multi-files
