### ISSUE TITLE
[BUG] Wrong setting panel shown when new component is added

### ISSUE THREAD

**Issue by manuongithub** [Kademi/keditor#198]
Wrong setting panel shown when new component is added

to reproduce:

1) open setting panel of any component.
2) add a component below the selected component
3) observe that even though the new component is selected yet the setting panel that is open is of the previous component...

If someone starts changing settings now then they'd reflect on the non-selected component.

A fix will be to open the settings panel of the newly added component.

**Comment by ducdhm** [comment]
Fixed!
