### ISSUE TITLE
[Feature request] close old setting panel before opening new setting panel

### ISSUE THREAD

**Issue by manuongithub** [Kademi/keditor#199]
**Functionality**
feature request is to close the settings panel of the old component before opening the setting panel of newly selected component.

Close with an animation of a closing drawer and open with animation of an open drawer.

This is good for UI as the user will see feedback to their actions.

**Comment by ducdhm** [comment]
Done!

**Comment by ducdhm** [comment]
@manuongithub please check it out ;)

**Comment by manuongithub** [comment]
thanks, but there is a small bug... the animation doesn't happen if changing between 2 same components... ex: changing between 2 image components...

**Comment by ducdhm** [comment]
@manuongithub I don't think it's good idea to animate same settings form for a component type. User can realize settings options changed when changing between 2 different components with same type.
