### ISSUE TITLE
IDs and Classes are removed from <section> containers [BUG]

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/keditor#202]
**Describe the bug**
Saving a page appears to be reducing `<section id="" class="">` to plain `<section>`.

**Version**
Latest version

**To Reproduce**
Simply saving the html page reduces the `<section>` containers to explicitly `<section>` removing any ID or Classes added to the container.

**Expected behavior**
Leave section containers as is with all attributes remaining on the tag. Example: `<section id="" class="" data-xxx="">...</section>`

**Additional context**
Often times when we get sign-off on a particular set of designs for sections on a webpage these designs are reverting back to default behaviour after a save. And it has been great being able to set an ID on a container and let the editor manage the inside content freely without having to train end user on learning to place classes and ids on inner containers just to get the bespoke design. This is an unnecessary headache and create huge levels of complexities.

Thanks for your time.

**Comment by bradmac** [comment]
@stephen-fueldesign just confirming you're aware this only applies to the section. You can just put IDs and classes on a div under the section

**Comment by stephen-fueldesign** [comment]
@bradmac Yes, I am aware. I will do further testing with the current jobs we have, and pages are breaking all over the place lately. I just feel if we can get IDs and/or Classes on a top-level section this mitigates end users from 1. breaking containers 2. giving freedom to create more rows and columns within a section 3. not needing to learn said classes or ids to apply to new rows and columns and containers.

**Comment by ducdhm** [comment]
@stephen-fueldesign Can you double-check again? With current commit, the ID and Classes of top section are keeping. You can check [this example](http://kademi.github.io/keditor/examples/basic_with_content.html)
