### ISSUE TITLE
[BUG] Starting with two content areas

### ISSUE THREAD

**Issue by hitaloramon** [Kademi/keditor#205]
This last commit has some bugs. Two content areas are always being created at startup.

Is the add content button now a component? If the person deleted no longer has a way to create new containers

Version
Last commit

Gif: `https://i.imgur.com/iVTaOyc.gifv`

**Comment by ducdhm** [comment]
@hitaloramon It works normal with current commit. And in next time, *PLEASE* write step by step to reproduce issue or I'll close issue as invalid because it's not following the BUG template
