### ISSUE TITLE
How to show the edit source button in ckeditor [BUG]

### ISSUE THREAD

**Issue by capricorn05** [Kademi/keditor#211]
**Describe the bug**
there is no view source or ability to edit the source of the text component
**Version**
Which version are you using?

**To Reproduce**
Add text component and try to edit it.  However the view source does not appear in the menu options

**Expected behavior**
Since ckeditor has the functionality to edit the source I would expect this to be available in this component.

**Comment by ducdhm** [comment]
@capricorn05 It's just CKEditor option inside KEditor. You can do it by yourself. Source code of text component at https://github.com/Kademi/keditor/blob/master/src/components/keditor-component-text.js#L11
