### ISSUE TITLE
[BUG] On ajax request it shows Only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by xposer** [Kademi/keditor#213]
**Describe the bug**
when i added function of Save button, it is sending data to post url, but it is not updating the data in data table. 
in console it is showing error : **Only one instance of babel-polyfill is allowed**

**Version**
Latest version

**To Reproduce**
Here is my Ajax request codes, 

```
<script type="text/javascript" data-keditor="script">
            $(function () {
                $('.content-area').keditor({
                         title: '<b>Drag and Drop</b>',
                             

                         onSave: function (content) {

                            $.ajax({
                                type: 'post',
                                data: { action: "send-content",
                                        content: console.log($('.content-area').keditor('getContent'))
                                    },
                               success: function (response) {
                                 $('#msg').html(response);
                             },
                             error: function (response) {
                              $('#msg').html(response);
                             }
                            });
                            
                            console.log($('.content-area').keditor('getContent'));
    },

                }
                    );

            });
        </script>
```

**Expected behavior**
It should save data into database. but it look like you are calling babel-polyfill function in two entries, 

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser: Chrome

**Comment by xposer** [comment]
PS: Here is full error detail, when Save button is clicked, also all the other data is updated in database. but this content-area is not updating/saving.

```
jquery.js:6 Uncaught Error: only one instance of babel-polyfill is allowed
    at Object.eval (eval at <anonymous> (jquery.js:4), <anonymous>:6:124026)
    at Object.eval (eval at <anonymous> (jquery.js:4), <anonymous>:6:124483)
    at e (eval at <anonymous> (jquery.js:4), <anonymous>:6:335)
    at Object.eval (eval at <anonymous> (jquery.js:4), <anonymous>:6:125035)
    at e (eval at <anonymous> (jquery.js:4), <anonymous>:6:335)
    at eval (eval at <anonymous> (jquery.js:4), <anonymous>:6:722)
    at eval (eval at <anonymous> (jquery.js:4), <anonymous>:6:733)
    at eval (<anonymous>)
    at jquery.js:4
    at Function.globalEval (jquery.js:4)
```

**Comment by ducdhm** [comment]
@xposer You did not specify `url` for your `$.ajax`. That's why content of KEditor not send to server.

**Comment by funnelhosts** [comment]
Hi, am unable to get the function of a save button to work. can you please check my code , am not sure if it's because I left something on my ajax request. Here is my code:

<?php
require "login/loginheader.php";
require "login/dbconf.php";
$dbconn = mysqli_connect($host,$username,$password,$db_name);

/*print_r($dbconn);*/

function clean($str){
	global $dbconn;
	$str =trim($str);
	$str=stripcslashes($str);
	$str=htmlentities($str,ENT_QUOTES);
	$str=mysqli_real_escape_string($dbconn,$str);
	return $str;
}

if(isset($_SESSION['username'])){
  $thisUser= clean($_SESSION['username']);

}


if(isset($_POST['action'])){

$content=mysqli_real_escape_string($dbconn,$_POST['content']);
$sql1="UPDATE `members` SET `content`='".$content."' WHERE `username`='".$thisUser."' ";
$query1=mysqli_query($dbconn,$sql1);

}
 ?>



<!DOCTYPE html>
<html lang="en">


    <body>

        <div data-keditor="html">
            <div id="content-area">

   

            </div>
        </div>




        	<script type="text/javascript" data-keditor="script">
            $(function () {
                $('#content-area').keditor({
                         onSave: function (content) {

                            $.ajax({
                                type: 'post',
                                data: { action: "send-content",
                                        content: $('#content-area').keditor('getContent')
                                      },

							 success: function(data) {
							console.log(data);
							},

							error: function(data) {
							console.log(data);
							}
								});

                            console.log($('#content-area').keditor('getContent'));
    },

                }
                    );

            });
        </script>
		   </body>
</html>

**Comment by funnelhosts** [comment]
I did not specify the url because the ajax request is going to be pushed back to the same page which will then push to the database.
