### ISSUE TITLE
How to add function of the save button on the page.

### ISSUE THREAD

**Issue by WayneMu** [Kademi/keditor#216]
I need help enable-ling  the function of a save button to work. can you please check my code , am not sure if it's because I left something on my ajax request. Here is my code:

<?php
require "login/loginheader.php";
require "login/dbconf.php";
$dbconn = mysqli_connect($host,$username,$password,$db_name);

/*print_r($dbconn);*/

function clean($str){
	global $dbconn;
	$str =trim($str);
	$str=stripcslashes($str);
	$str=htmlentities($str,ENT_QUOTES);
	$str=mysqli_real_escape_string($dbconn,$str);
	return $str;
}

if(isset($_SESSION['username'])){
  $thisUser= clean($_SESSION['username']);

}

if(isset($_POST['action'])){

$content=mysqli_real_escape_string($dbconn,$_POST['content']);
$sql1="UPDATE `members` SET `content`='".$content."' WHERE `username`='".$thisUser."' ";
$query1=mysqli_query($dbconn,$sql1);

}
 ?>

<!DOCTYPE html>
<html lang="en">

    <body>

        <div data-keditor="html">
            <div id="content-area">

   

            </div>
        </div>

        	<script type="text/javascript" data-keditor="script">
            $(function () {
                $('#content-area').keditor({
                         onSave: function (content) {

                            $.ajax({
                                type: 'post',
                                data: { action: "send-content",
                                        content: $('#content-area').keditor('getContent')
                                      },

							 success: function(data) {
							console.log(data);
							},

							error: function(data) {
							console.log(data);
							}
								});

                            console.log($('#content-area').keditor('getContent'));
    },

                }
                    );

            });
        </script>
		   </body>
</html>

 

I did not specify the url because the ajax request is going to be pushed back to the same page which will then push to the database.it`s not showing any error massages.

**Version**
Latest Version

**Expected behavior**
When I click the save button I was expecting to see my code on console and submit to database.

**Desktop**
.OS:Windows 10
.Browser: Chrome

**Comment by ducdhm** [comment]
@WayneMu 
1. You dont need call `getContent` method to get the current content. You can use `content` param of `onSave` callback, it's current content. 
2. You need to check your server log to know what happens in server. This part is related to you so I can't help you.

Thanks for using KEditor,
/Duc
