### ISSUE TITLE
Is possible to add other types of components? Like react native pages?

### ISSUE THREAD

**Issue by diaraujo13** [Kademi/keditor#217]

**Comment by bradmac** [comment]
yes, eg in kademi.co we have hundreds of custom components

Its very flexible. in our usage these are generated dynamically in an ajax service depending on the type of page being edited.

**Comment by ducdhm** [comment]
@diaraujo13 You can follow [this guide](https://github.com/Kademi/keditor/blob/master/docs/custom_component.md) to create your own component.

Thanks,
/Duc
