### ISSUE TITLE
Bootstrap 4 support ?

### ISSUE THREAD

**Issue by NicolasCKC** [Kademi/keditor#218]
System is still using boostrap 3, is there a plan to use bootstrap 4 instead & if yes, when?

**Comment by anhnt** [comment]
We dont have plan to support BS4 in the near future. PR are always welcomed :)

**Comment by NicolasCKC** [comment]
thanks for the fast answer! any idea on how much dev time it would be approx?

**Comment by bradmac** [comment]
My guess is about a day of updating and tweaking css.

I think this should be managed as a seperate major version (probably in a seperate repo), because many users (like us) have extended keditor with hundreds more components, and those would need to be upgraded as well which would be a much larger effort.

So we need to continue supporting bs3 for quite some time yet.

**Comment by ducdhm** [comment]
@NicolasCKC Please take a look at configuration of KEditor. We already have setting for Bootstrap which allows you to use BS4.

```
    bootstrap: {
        /**
         * Enable column resize by drag and drop or not. Require: jQuery UI Resizable
         * @option {Boolean}
         */
        columnResizeEnabled: true,
        
        /**
         * List of device class for responsive grid system
         * @option {Object}
         */
        deviceClass: {
            MOBILE: 'xs',
            TABLET: 'sm',
            LAPTOP: 'md',
            DESKTOP: 'lg'
        },
        
        /**
         * Grid system of bootstrap with `width` in percentage and `col` number
         * @option {Array<Object>}
         */
        gridSystem: [{
            width: 8.33333333,
            col: 1
        }, {
            width: 16.66666667,
            col: 2
        }, {
            width: 25,
            col: 3
        }, {
            width: 33.33333333,
            col: 4
        }, {
            width: 41.66666667,
            col: 5
        }, {
            width: 50,
            col: 6
        }, {
            width: 58.33333333,
            col: 7
        }, {
            width: 66.66666667,
            col: 8
        }, {
            width: 75,
            col: 9
        }, {
            width: 83.33333333,
            col: 10
        }, {
            width: 91.66666667,
            col: 11
        }, {
            width: 100,
            col: 12
        }, {
            width: 10000,
            col: 10000
        }]
    },
```
Link for details: https://github.com/Kademi/keditor/blob/master/src/keditor/constants/defaults.js#L336

**Comment by anabeatrizzz** [comment]
@NicolasCKC hello, I would like an example of how to add a success Bootstrap button to the components. I didn't understand what I have to specify in the handler file.
