### ISSUE TITLE
[BUG] Popup  is not working( prove is not displaying )

### ISSUE THREAD

**Issue by kprasadbabu7** [Kademi/keditor#223]
![image](https://user-images.githubusercontent.com/44153959/77731605-3ac23e80-7029-11ea-94e5-cfbfd9c97420.png)

when we click tho add (+) button popup is coming but that is empty .How can we fix that  Please share me the code

**Comment by ducdhm** [comment]
@kprasadbabu7 Please kindly give me more details which version you're using, the code snippet, etc...
