### ISSUE TITLE
Adding new components

### ISSUE THREAD

**Issue by anabeatrizzz** [Kademi/keditor#225]
Hello,
I wish to drag and drop a table when the **+** symbol is clicked but I didn't understand how to add components.
Can someone explain to me in detail? Thank you.

**Comment by bradmac** [comment]
Hi @anabeatrizzz 

The first version of keditor had a side panel to drag and drop from. However this caused some UX issues, so in version2 when you click the + button the user is shown all available components. Selecting a component adds it to the page in the location of the + button

It can then be dragged to another location, but its usually easiest for users to click the + button at the location they want to add.

**Comment by anabeatrizzz** [comment]
@bradmac but how can I add a table in those all available components?

**Comment by bradmac** [comment]
There's no table component that i know of. But you can just add the text component which is edited with ckeditor, which has tables.

And of course you can build your own table component :)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/77835374-d8944580-71b0-11ea-9970-992defa101de.png)

**Comment by anabeatrizzz** [comment]
> There's no table component that i know of. But you can just add the text component which is edited with ckeditor, which has tables.
> 
> And of course you can build your own table component :)

Exactly! I want to build and drag n drop a table com this appearence:
![Captura de tela_2020-03-28_19-33-26](https://user-images.githubusercontent.com/53445202/77835455-7d6c3f80-712b-11ea-96f5-48956b6de7a9.png)

How can I accomplish that?

**Comment by bradmac** [comment]
There are instructions here for building and contributing components

https://github.com/Kademi/keditor/blob/master/docs/contribute_a_component.md

**Comment by anabeatrizzz** [comment]
> There are instructions here for building and contributing components
> 
> https://github.com/Kademi/keditor/blob/master/docs/contribute_a_component.md

Yes, I already read this instructions but I didn't understand the handler file part. Do I have to change anything? Do I have to change lines with `@param {jQuery}` or `@param {KEditor}`, for instance?

**Comment by bradmac** [comment]
@param is for code comments. You can look at documentation for javascript for information about that.
