### ISSUE TITLE
Bootstrap collapse, tabs, slider does not navigate elements

### ISSUE THREAD

**Issue by hitaloramon** [Kademi/keditor#231]
@ducdhm do you have any idea why when, for example i use a collapse or tabs from boostrap i can't open, or navigate through the elements? I tried to inject javascript so that these elements would work at least in preview mode, but without success. I was looking to develop some components for keditor, but I would need these bootstrap components to take effect inside the editor, similar to the hyper editor:

https://divineitlimited.github.io/hyper-editor/demo.html

sorry for my English

**Comment by ducdhm** [comment]
@hitaloramon your question is so common. Please provide me your code snippet to investigate.

FYI: By default, all anchors inside keditor is disable click event. If you want to use Bootstrap, you need to inject Bootstrap JS inside KEditor.

**Comment by shoaibSia** [comment]
@ducdhm I also need this effect to be done. Can you please tell how to enable click event on editor or how to add Bootstrap JS inside KEditor.
