### ISSUE TITLE
[BUG] thumbnail panel does not allow editing the image

### ISSUE THREAD

**Issue by daniel-olmos** [Kademi/keditor#232]
**Describe the bug**
when trying to edit the thumbnail panel image, it does not show any option, so it does not allow adding a new image

**Version**
v.2.0.0

**To Reproduce**
go to Ckeditor, enter the builder, and select the thumbnail panel element, once inserted, try to change the image

**Expected behavior**
open an edit panel like the one in the image, where you can upload an image from the desktop or through a link

**Screenshots**
![image](https://user-images.githubusercontent.com/13950641/80784045-14288380-8b52-11ea-9420-188d9da711f0.png)

**Desktop (please complete the following information):**
 - OS: [W10]
 - Browser [chrome]
 - Version [81.0.4044.129 (Build oficial) (64 bits)]

**Additional context**

**Comment by ducdhm** [comment]
Fixed!

**Comment by daniel-olmos** [comment]
Perfect!

Thanks @ducdhm
