### ISSUE TITLE
Drag and Drop wherever I want 

### ISSUE THREAD

**Issue by abdullahniazi96** [Kademi/keditor#262]
Is there any way to drag and drop elements wherever I want on page. Without auto alignment into grids or columns.
just randomly on the page.

**Comment by bradmac** [comment]
Then responsive layout would be impossible, so not a good idea.

Just use powerpoint :)

**Comment by abdullahniazi96** [comment]
@bradmac 
Yes I know you are right.
but client wants this .[Draggable Div](http://plnkr.co/edit/ZwiDo9gx5nAcz4Z0daTo?p=preview&preview)

**Comment by bradmac** [comment]
Good luck with that :)

**Comment by bigheroai** [comment]
drag n drop is possible every other builder has this basic feature

**Comment by bradmac** [comment]
yes keditor supports drag and drop :)
