### ISSUE TITLE
Select Filter in the Snippets

### ISSUE THREAD

**Issue by hitaloramon** [Kademi/keditor#29]
It would be possible to add a filter to select between similar snippets to this system:

http://www.innovastudio.com/builderdemo/example1.html

**Comment by bradmac** [comment]
I think that would be good. But also, i think it would be good to have a search option.

What i think is that snippets should be associated with multiple tags. A list of available tags is shown to allow selecting from. There is also a search box. A user can type in keywords and the list will be dynamically filtered by searching for the keywords in title/tags/description

**Comment by ducdhm** [comment]
Separate issue for searchable https://github.com/Kademi/keditor/issues/34
