### ISSUE TITLE
IS kEditor is wokring with  dynamically created content area 

### ISSUE THREAD

**Issue by jyoti22p** [Kademi/keditor#32]
Actually I am using Kademi content editor   with drag and drop  section
	
but i want multiple content area with dynamically create element
	
how we can do that
	
https://rawgit.com/Kademi/keditor/master/examples/multi_content_area.html
	
I am using this demo
	
Is it possible to do with dynamic create content area ?

**Comment by bradmac** [comment]
Yep, that should be no trouble at all. Have you seen any problems?

**Comment by jyoti22p** [comment]
yes   I am facing problem   to create multiple content area dynamically   to drag the  container and components  . Can you please provide me example regarding this or some code help .I am stuck over there

**Comment by ducdhm** [comment]
@jyoti22p Is it what you want?

```html
        <div id="keditor">
            <div id="header"></div>
            <div id="body"></div>
            <div id="footer"></div>
        </div>
```

```javascript
        $('#keditor').keditor({
	        contentAreasSelector: '#header, #body, #footer'
        });
```
