### ISSUE TITLE
Keditor in angular js

### ISSUE THREAD

**Issue by umarch06** [Kademi/keditor#38]
Hey,
I appreciate this plugin very much because of it's extra ordinary beauty. Can you please provide me link of **angular directive** for this plugin?
Appreciations.

**Comment by ducdhm** [comment]
We just maintain jquery version for KEditor now. Will create repo for Angular Directive soon.

**Comment by Dhara-ZYMR** [comment]
Any updates regarding Angular Directive?
If not can you please provide a guideline to create one.
