### ISSUE TITLE
getContent does not work

### ISSUE THREAD

**Issue by Audax23** [Kademi/keditor#42]
Hello, 
I would like to get the content but it doesn't work, i use this as explain in doc.
$('#id').keditor('getContent');
 jquery return Uncaught TypeError: jQuery(...).keditor is not a function
how to resolve this ?
thank you

**Comment by bradmac** [comment]
That error means you the keditor plugin hasnt been loaded. Please check you have included the js file, and in the correct order.

**Comment by Audax23** [comment]
thank you, i test on blank.html demo, it works fine.
great tools !
