### ISSUE TITLE
Dynamic content remove data-dynamic-href div

### ISSUE THREAD

**Issue by hitaloramon** [Kademi/keditor#45]
Is it possible that when dynamic content is added to the contentarea it deletes the line where the dynamic content comes from?

To remove the div containing the data-dynamic-href

I do not know if it's clear, sorry, my English

**Comment by ducdhm** [comment]
@hitaloramon As I understand, you want to remove the element which contains `data-dynamic-href`?

If yes, we have a callback will be called after dynamic content is loaded

```
/*
 * @option {Function} onDynamicContentLoaded Callback will be called after dynamic content is loaded. Arguments: dynamicElement, response, status, xhr
*/
...
    onDynamicContentLoaded: function (dynamicElement, response, status, xhr) {
    }
...
```
