### ISSUE TITLE
Lived examples don't work

### ISSUE THREAD

**Issue by Roko131** [Kademi/keditor#48]
In readme this link- https://github.com/Kademi/keditor#lived-examples leads to an example page:
https://rawgit.com/Kademi/keditor/master/examples/index.html

Which has some examples, like this one:
https://rawgit.com/Kademi/keditor/master/examples/multi_content_area.html
But none of them work..

p.s.
Shouldn't it be Live examples and not Lived examples?

![image](https://cloud.githubusercontent.com/assets/3532929/24332298/e7e44e0c-124c-11e7-90bb-aed2dded70bc.png)

**Comment by bradmac** [comment]
:+1: 

@ducdhm can you update the examples?

**Comment by ducdhm** [comment]
Done!
