### ISSUE TITLE
KEditor doesn't work on touch devices

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/keditor#5]
KEditor should support touch devices like Tablets (Android, Apple and Microsoft)

**Comment by ducdhm** [comment]
@bradmac @anhnt What do you think about it?

**Comment by bradmac** [comment]
Yep, i think it should. Pretty sure our customers would love to drag and drop with their touch screens.

**Comment by ducdhm** [comment]
Found this one for enable DnD on touch device http://touchpunch.furf.com/

**Comment by ducdhm** [comment]
You can follow this guide at https://github.com/Kademi/keditor#support-touch-devices.
You also can check lived example with support device touch at https://rawgit.com/Kademi/keditor/master/examples/support_touch_device.html
