### ISSUE TITLE
idea: draggable columns?

### ISSUE THREAD

**Issue by remcovo** [Kademi/keditor#50]
I came across this solutions to drag and change columns widths, maybe this can be very handy and easy to intergrate. (I am not a js specialist -sorry).

http://jsfiddle.net/onigetoc/ag4mgpbs/

If you also take note of the viewport (like the editor is viewed in an resizable iframe) this might be very handy solution to resize columns for small, medium and large views.
And create something very userfriendly  like http://shoelace.io

**Comment by ducdhm** [comment]
Hi @remcovo, basically KEditor just provides you a content editor core with drag and drop snippet feature.  KEditor  also supports a lot of callback for events as well as allows developers extend it with customized snippets and component types. For draggable columns, you can implement it by your self via `containerSettingInitFunction` method or `onInitContainer` callback
