### ISSUE TITLE
build process doesn't seem to be working

### ISSUE THREAD

**Issue by rip747** [Kademi/keditor#55]
I might just be not understanding how the build process works. I'm getting alot more files in the dist folder than in the previous release. I preformed the build using "gulp build", I am doing something wrong? Below is a "git status" after running the build process.

On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    dist/css/keditor-1.1.4.css
	deleted:    dist/css/keditor-1.1.4.min.css
	deleted:    dist/css/keditor-1.1.4.min.css.map
	deleted:    dist/css/keditor-components-1.1.4.css
	deleted:    dist/css/keditor-components-1.1.4.min.css
	deleted:    dist/css/keditor-components-1.1.4.min.css.map
	deleted:    dist/js/keditor-1.1.4.js
	deleted:    dist/js/keditor-1.1.4.min.js
	deleted:    dist/js/keditor-1.1.4.min.js.map
	deleted:    dist/js/keditor-components-1.1.4.js
	deleted:    dist/js/keditor-components-1.1.4.min.js
	deleted:    dist/js/keditor-components-1.1.4.min.js.map
	modified:   src/css/keditor.css

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	dist/css/keditor-1.1.5.css
	dist/css/keditor-1.1.5.min.css
	dist/css/keditor-1.1.5.min.css.map
	dist/css/keditor-bootstrap-form-1.1.5.css
	dist/css/keditor-bootstrap-form-1.1.5.min.css
	dist/css/keditor-bootstrap-form-1.1.5.min.css.map
	dist/css/keditor-component-text-1.1.5.css
	dist/css/keditor-component-text-1.1.5.min.css
	dist/css/keditor-component-text-1.1.5.min.css.map
	dist/css/keditor-components-1.1.5.css
	dist/css/keditor-components-1.1.5.min.css
	dist/css/keditor-components-1.1.5.min.css.map
	dist/js/keditor-1.1.5.js
	dist/js/keditor-1.1.5.min.js
	dist/js/keditor-1.1.5.min.js.map
	dist/js/keditor-component-audio-1.1.5.js
	dist/js/keditor-component-audio-1.1.5.min.js
	dist/js/keditor-component-audio-1.1.5.min.js.map
	dist/js/keditor-component-googlemap-1.1.5.js
	dist/js/keditor-component-googlemap-1.1.5.min.js
	dist/js/keditor-component-googlemap-1.1.5.min.js.map
	dist/js/keditor-component-photo-1.1.5.js
	dist/js/keditor-component-photo-1.1.5.min.js
	dist/js/keditor-component-photo-1.1.5.min.js.map
	dist/js/keditor-component-text-1.1.5.js
	dist/js/keditor-component-text-1.1.5.min.js
	dist/js/keditor-component-text-1.1.5.min.js.map
	dist/js/keditor-component-video-1.1.5.js
	dist/js/keditor-component-video-1.1.5.min.js
	dist/js/keditor-component-video-1.1.5.min.js.map
	dist/js/keditor-component-vimeo-1.1.5.js
	dist/js/keditor-component-vimeo-1.1.5.min.js
	dist/js/keditor-component-vimeo-1.1.5.min.js.map
	dist/js/keditor-component-youtube-1.1.5.js
	dist/js/keditor-component-youtube-1.1.5.min.js
	dist/js/keditor-component-youtube-1.1.5.min.js.map
	dist/js/keditor-components-1.1.5.js
	dist/js/keditor-components-1.1.5.min.js
	dist/js/keditor-components-1.1.5.min.js.map

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by rip747** [comment]
see: fix build process #56

**Comment by ducdhm** [comment]
@rip747 It's working. I just added js files for each components.
