### ISSUE TITLE
Textarea and iframe in Firefox

### ISSUE THREAD

**Issue by hessian0** [Kademi/keditor#58]
There is an issue with loaded contents if textarea is used in iframeMode
Thank you for the great tool tho

**Comment by ducdhm** [comment]
@hessian0 Can you provide me link to codepen or jsfiddle for demo this issue?

**Comment by hessian0** [comment]
@ducdhm Here a link to  [jsfiddle](https://jsfiddle.net/evdq480n/3) demo with textarea and iframeMode enabled.
Replacing _textarea_ with _div_ (or setting iframeMode=false) contents are loaded fine (except with FF that in my tests doesn't work with iframe at all).
Thank you for the help

**Comment by ducdhm** [comment]
@hessian0 I pushed the fix in version 1.1.5. It's working now! You can check demo at https://jsfiddle.net/evdq480n/5/
