### ISSUE TITLE
Adding plugins to ckeditor toolbar

### ISSUE THREAD

**Issue by webauthor** [Kademi/keditor#59]
Hi, great tool.  I already using ckeditor and would like to add one or more plugins to the toolbar.  Can you point me in the right direction?

Thanks.

**Comment by anhnt** [comment]
You can create your custom text component and add your custom ckeditor plugins then rebuild keditor

See here for example https://github.com/Kademi/keditor/blob/master/src/js/keditor-component-text.js

**Comment by webauthor** [comment]
Excellent.  Thank you so much.
