### ISSUE TITLE
Filters not shown

### ISSUE THREAD

**Issue by SadokLadhari** [Kademi/keditor#62]
In the `renderSnippets` function categories are retrieved by the attribute `data-keditor-categories` : 
`                var categories = snippet.attr('data-keditor-categories') || '';`
or in the snippets.html we have just `data-categories` not `data-keditor-categories` ??

I changed the attribute to `data-keditor-categories` , so that the filters appears.

**Comment by ducdhm** [comment]
@SadokLadhari Really thanks for this. I changed `data-category` to `data-keditor-category` because my custom component has `data-category` for its dynamic element.

**Comment by ducdhm** [comment]
Fixed!
