### ISSUE TITLE
Blocks duplucation

### ISSUE THREAD

**Issue by Rilvatore** [Kademi/keditor#69]
Hello,

I have a issue with blocks (div,p, section..) which, fairly rarely, duplicate without any reason in the editor (which use the ckeditor plugin). The problem is that it appears randomly without any HTML structure modification. I have tried to clear the cache on each reload of the page editor but it has no effect. I noticed that the issue usually appears in Safari, never with Chrome in my tests.
I specify that my HTML content is validated with the W3C validator.

Sorry for my bad english..

**Comment by ducdhm** [comment]
@Rilvatore Can you provide me more information, something like your HTML code?

**Comment by Rilvatore** [comment]
Yes, here is an exctract of HTML code that, sometimes, duplicate in the editor:

`<div class="blue-line"><div class="wrapper" data-type="container-content"><section data-type="component-text"><a class="btn-asd btn-asd-white" href="/my-asd/connexion?next_url=http%3A%2F%2Fwww.asd-int.com%2Fmy-asd">Commencez dès maintenant</a></section></div></div>`

The problem is that sometimes (very fearly), when I save the page (with ajax I send the content of the Keditor content to my database), I have this result (save exactly like that in my database) without any reason:

`<div class="blue-line"><div class="wrapper" data-type="container-content"><section data-type="component-text"><a class="btn-asd btn-asd-white" href="/my-asd/connexion?next_url=http%3A%2F%2Fwww.asd-int.com%2Fmy-asd">Commencez dès maintenant</a></section><section data-type="component-text"><a class="btn-asd btn-asd-white" href="/my-asd/connexion?next_url=http%3A%2F%2Fwww.asd-int.com%2Fmy-asd">Commencez dès maintenant</a></section></div></div>`

This issue can appear when I modify the content in an other part of the page without touch this one.
I know it's very strange..

**Comment by ducdhm** [comment]
@Rilvatore Which version KEditor are you using?

**Comment by Rilvatore** [comment]
I use the 1.1.5 version. When I saw I had problems of duplication, I upgraded the plugin (the first version i had was 1.1.3).
Yes I use the `keditor('getContent')` property to get the content of my editor.

**Comment by Rilvatore** [comment]
I thank it's very strange also for you... ;)
Do you have any other idea where I could search in the plugin to resolve this issue?

**Comment by ducdhm** [comment]
@Rilvatore I checked 3 times with your HTML data and I could not reproduce this issue. So... I have no idea how it happens. It'll be good if we have real code in action for checking.

**Comment by Rilvatore** [comment]
Again thank you for your response. Here is an example of complete HTML content for a page edited with keditor:

`<section>[WHEEL_MANDATAIRES]
	<div class="service-page">
		<div class="grey-line">
			<div class="wrapper">
				<div class="row">
					<div class="col-md-3 first-col" data-type="container-content"><section data-type="component-text"><img alt="" src="/assets/admin/js/keditor/examples/plugins/ckeditor-4.5.6/plugins/imageuploader/uploads/23203a69a.jpg" style="width: 400px; height: 250px;"></section></div>
					<div class="col-md-9 second-col">
						<div data-type="container-content" class=""><section data-type="component-text"><h2>DÉFINITION DU DÉTACHEMENT DE TRAVAILLEURS</h2>
</section></div>
						<div class="blocks" data-type="container-content"><section data-type="component-text"><p dir="ltr">Détacher des travailleurs étrangers sur le territoire français est une pratique très encadrée par la loi. Chaque employeur étranger réalisant des prestations en France doit respecter les lois sociales françaises pour ses salariés détachés, notamment les obligations déclaratives, la rémunération et les conditions de travail (temps de travail, temps de repos, etc.). En cas de non respect de ces lois, des sanctions peuvent s'appliquer.</p>
</section><section data-type="component-text"><p><a class="blue-button block" href="/contact"><img alt="" class="normal" src="/image/icon-mandataire-white-block-1.png"> <img alt="" class="hover" src="/image/icon-mandataire-white-block-1-hover.png"> <span>Téléchargez<br>
le Livre Blanc</span> </a> <a class="blue-button block" href="http://www.soposting-worker.com/"> <img alt="" class="normal" src="/image/icon-mandataire-white-block-2.png"> <img alt="" class="hover" src="/image/icon-mandataire-white-block-2-hover.png"> <span>Téléchargez notre brochure - Secteur du Transport</span> </a> <a class="blue-button block" href="http://www.sotruck-app.com/"> <img alt="" class="normal" src="/image/icon-mandataire-white-block-2.png"> <img alt="" class="hover" src="/image/icon-mandataire-white-block-2-hover.png"> <span>Téléchargez notre brochure - Secteur du BTP et autre</span> </a></p>
</section></div>
					</div>
				</div>
			</div>
		</div>
		<div class="white-line">
			<div class="wrapper">
				<div data-type="container-content" class=""><section data-type="component-text"><div class="separator-block">
<h2>RÈGLES ET CONDITIONS DU DÉTACHEMENT SALARIAL</h2>

<div class="separator" style="color: rgb(51, 51, 51); font-size: 14px; font-weight: 300;">
<div class="element line">&nbsp;</div>

<div class="element square">&nbsp;</div>

<div class="element line">&nbsp;</div>

<div class="clear">&nbsp;</div>
</div>
</div>
</section></div>
				<div class="row">
					<div class="col-md-6 first-col" data-type="container-content"><section data-type="component-text" data-title="Text block"><h3><span style="font-size:18px;">Le détachement d’un salarié par une entreprise étrangère implique certaines conditions obligations telles que :&nbsp;</span></h3>

<p>&nbsp;</p>
</section><section data-type="component-text"><p class="list">Le paiement du salaire minimum français (les cotisations sociales restent dues dans le pays d’origine)</p>

<p class="list">Le temps de travail des salariés</p>

<p class="list">Désigner un représentant en France servant de liaison entre les autorités françaises et l’entreprise étrangère</p>

<p class="list">Remplir une déclaration préalable de détachement sur le site officiel du ministère du travail SIPSI (une déclaration par travailleur détaché)</p>

<p class="list">Pour le secteur du transport, obtenir des vignettes Crit'Air</p>

<p class="list">Obtenir <a href="https://www.cartebtp.fr">une carte BTP</a> pour chaque salarié détaché (pour le secteur du BTP). Pour en savoir plus sur la carte BTP, consultez&nbsp;notre page : <a href="/actualites/article/16-tout-savoir-sur-la-carte-btp-pour-les-travailleurs-detaches">Qu'est-ce-que la carte BTP et comment l'obtenir ?</a></p>

<p class="list">Informer les salariés des chantiers sur leurs conditions et leurs droits de travail via un affichage et un document d'information obligatoires&nbsp;traduit dans les langues des travailleurs.</p>
</section><section data-type="component-text"><div class="text-center"><a class="btn-asd btn-asd-blue m-t-30 m-b-30 p-l-20 p-r-20 show-btp-documents-order-modal" href="/my-asd/commande-documents-information-detachements-salaries">Téléchargez le document d'information des salariés détachés</a></div>
</section></div>
					<div class="col-md-6 second-col" data-type="container-content"><section data-type="component-text" data-title="Text block"><div class="text-center"><img alt="" src="/assets/admin/js/keditor/examples/plugins/ckeditor-4.5.6/plugins/imageuploader/uploads/231cec687.jpg" style="width: 320px; height: 250px;"></div>

<p class="text-center">&nbsp;</p>
</section><section data-type="component-text"><h3 style="text-align: center;"><span style="color:#3399ff;">LES NOTIONS À RETENIR</span></h3>

<h3 style="text-align: center;">&nbsp;</h3>
</section><section data-type="component-text"><div class="row vcenter-mobile">
<div class="col-xs-3 text-right"><img alt="premier point à retenir sur le détachement de salarié en France" height="74" src="/assets/admin/js/keditor/examples/plugins/ckeditor-4.5.6/plugins/imageuploader/uploads/393f97a3.png" style="width: 74px; height: 74px;" width="74"></div>

<div class="col-xs-9">
<p><font size="4">L</font>es règles relatives aux détachement de travailleurs étrangers en France concernent toutes les sociétés établies hors de France.</p>
</div>
</div>
</section><section data-type="component-text"><div class="row vcenter-mobile">
<div class="col-xs-3 text-right"><img alt="deuxième point essentiel concernant le détachement de travailleurs étrangers en France" src="/assets/admin/js/keditor/examples/plugins/ckeditor-4.5.6/plugins/imageuploader/uploads/47d851ad.png" style="width: 74px; height: 74px;"></div>

<div class="col-xs-9">
<p>Des sanctions financières sont appliquées en cas de non respect de la loi.</p>
</div>
</div>
</section><section data-type="component-text"><div class="row vcenter-mobile">
<div class="col-xs-3 text-right"><img alt="quatrième notion sur le détachement de travailleurs non français" src="/assets/admin/js/keditor/examples/plugins/ckeditor-4.5.6/plugins/imageuploader/uploads/40dae65e.png" style="height: 74px; width: 74px;"></div>

<div class="col-xs-9">
<p>Obligation de respecter le droit social en France, notamment en terme de salaire.</p>
</div>
</div>
</section><section data-type="component-text"><div class="row vcenter-mobile">
<div class="col-xs-3 text-right"><img alt="cinquième et dernier point essentiel à retenir sur le détachement de personnel en France" src="/assets/admin/js/keditor/examples/plugins/ckeditor-4.5.6/plugins/imageuploader/uploads/419bb027.png" style="width: 74px; height: 74px;"></div>

<div class="col-xs-9">
<p>Remplir une déclaration préalable de détachement sur le site officiel du ministère du travail et en cas d'accident de travail.</p>
</div>
</div>
</section><section data-type="component-text"><div class="row vcenter-mobile">
<div class="col-xs-3 text-right"><img alt="cinquième et dernier point essentiel à retenir sur le détachement de personnel en France" height="74" src="/assets/admin/js/keditor/examples/plugins/ckeditor-4.5.6/plugins/imageuploader/uploads/42291faa.png" style="width: 74px; height: 74px;" width="74"></div>

<div class="col-xs-9">
<p>Les obligations pour le secteur du BTP et du transport diffèrent des règles générales.</p>
</div>
</div>
</section></div>
				</div>
			</div>
		</div>
		<div class="video-line">
		<div class="wrapper">
				<div class="row">
					<div class="col-md-12" data-type="container-content">

					<section data-type="component-text"><div class="separator-block">
<p><span style="font-size:20px;"><strong>ASD Group a mis en place deux services dédiés à cette activité.&nbsp;​</strong></span></p>
</div>
</section></div>
					<div class="col-md-6 col-video">
						<div class="video" data-type="container-content"><section data-type="component-text"><p dir="ltr" style="text-align: center;"><a href="http://www.sotruck-app.com"><img alt="" src="/assets/admin/js/keditor/examples/plugins/ckeditor-4.5.6/plugins/imageuploader/uploads/220ff5dfa.png" style="width: 125px; height: 80px;"></a></p>

<p dir="ltr" style="text-align: center;"><strong>Gestion des salariés détachés en France dans le transport (roulants ou navigants)</strong></p>
</section><section data-type="component-text"><div class="youtube-embed-wrapper" style="position:relative;padding-bottom:56.25%;padding-top:30px;height:0;overflow:hidden;"><iframe allowfullscreen="" frameborder="0" height="360" kwframeid="2" src="//www.youtube.com/embed/2j2nOIqjZk4?rel=0" style="position: absolute;top: 0;left: 0;width: 100%;height: 100%;" width="640"></iframe></div>
</section><section data-type="component-text"><p dir="ltr" style="text-align: center;">&nbsp;</p>

<p dir="ltr" style="text-align: justify;">Vous êtes impacté par les obligations de la loi sur la concurrence déloyale et par la loi Macron? Vous recherchez un expert, parlant votre langue, en détachement de travailleurs étrangers en France? ASD Group peut vous répondre et vous accompagner dans vos démarches obligatoires via sa plateforme en ligne : déclarations, représentation, gestion des contrôles, documents obligatoires, vignettes Crit'Air. Assurez-vous de votre conformité, et diminuez ainsi vos risques financiers en cas de contrôle.</p>

<p dir="ltr" style="text-align: justify;">Visitez notre site Internet :<a href="http://www.sotruck-app.com"> www.sotruck-app.com</a></p>
</section></div>
					</div>
					<div class="col-md-6" data-type="container-content"><section data-type="component-text"><p dir="ltr" style="text-align: center;"><a href="http://www.sotruck-app.com"><img alt="" src="/assets/admin/js/keditor/examples/plugins/ckeditor-4.5.6/plugins/imageuploader/uploads/233c76bfd.png" style="width: 133px; height: 80px;"></a></p>

<p dir="ltr" style="text-align: center;"><strong>Gestion des salariés détachés en France dans le BTP et tous les autres secteurs&nbsp;(hors Transport)</strong></p>
</section><section data-type="component-text"><div style="text-align:center"><a href="http://www.soposting-worker.com/" target="_blank"><img alt="Image de la page d'accueil du site SoTruck. Application web sur le détachement de salarié étranger en France" src="/assets/admin/js/keditor/examples/plugins/ckeditor-4.5.6/plugins/imageuploader/uploads/222afd099.png" style="width: 464px; height: 350px;"></a></div>

<p align="JUSTIFY">&nbsp;</p>

<p align="JUSTIFY">Vous détachez des salariés sur des chantiers ou dans d'autres secteurs? ASD Group a développé une plateforme en ligne vous permettant de gérer entièrement vos obligations selon le domaine d'activité désiré : représentation, déclarations, documents obligatoires, carte BTP, document d'information des salariés détachés, affichage obligatoire.</p>

<p align="JUSTIFY">&nbsp;</p>

<p align="JUSTIFY">Visitez notre site Internet : <a href="http://www.soposting-worker.com" target="_blank">www.soposting-worker.com</a></p>
</section></div>
				</div>
			</div>
		</div>
		<div class="dark-line">
			<div class="wrapper">
				<div data-type="container-content" class=""><section data-type="component-text"><div class="separator-block">
<h3>&nbsp;CE QUE ASD GROUP PEUT FAIRE POUR VOUS</h3>

<div class="separator" style="font-size: 14px; font-weight: 300;">
<div class="element line">&nbsp;</div>

<div class="element square">&nbsp;</div>

<div class="element line">&nbsp;</div>

<div class="clear">&nbsp;</div>
</div>
</div>
</section></div>
				<div class="row cols">
					<div class="col-md-5 first-col" data-type="container-content"><section data-type="component-text"><p>ASD Group a développé 2 plateformes de gestion de détachement, So Truck pour le transport, So Posting Worker pour le BTP et les autres secteurs.</p>

<p>Ces plateformes en ligne vous permettent de gérer toutes les obligations relatives au détachement telles que le stockage des documents obligatoires, la gestion de vos salariés détachés, les demandes de SIPSI ou de cartes BTP et bien d'autres choses.&nbsp;</p>

<p>Pour en savoir plus, rendez-vous sur nos pages de <a href="http://www.soposting-worker.com">So Posting Worker</a> et de<a href="http://www.sotruck-app.com"> So Truck.</a></p>
</section></div>
					<div class="col-md-7 second-col">
						<div class="row">					
							<div class="col-md-4 block" data-type="container-content"><section data-type="component-text"><p><img alt="Icon - représentation" height="74" src="/assets/admin/js/keditor/examples/plugins/ckeditor-4.5.6/plugins/imageuploader/uploads/44f8bb62.png" width="74"></p>

<h5>représentant français</h5>

<p>ASD Group vous représentera en France et fera le lien entre vous et les autorités françaises</p>
</section></div>
							<div class="col-md-4 block" data-type="container-content"><section data-type="component-text"><p><img alt="icon - gestion de dossier " height="74" src="/assets/admin/js/keditor/examples/plugins/ckeditor-4.5.6/plugins/imageuploader/uploads/45b1e1c0.png" width="74"></p>

<h5>gestion de votre dossier</h5>

<p>Nous prenons en charge votre dossier dans son intégralité. Tout&nbsp;est&nbsp;inclus</p>
</section></div>
							<div class="col-md-4 block" data-type="container-content"><section data-type="component-text"><p><img alt="Icon - Assistance en cas de contrôle" height="74" src="/assets/admin/js/keditor/examples/plugins/ckeditor-4.5.6/plugins/imageuploader/uploads/457c7821.png" width="74"></p>

<h5>assistance en cas de contrÔle</h5>

<p>Nous intervenons en cas de contrôle de gendarmerie ou de l'inspection du travail</p>
</section></div>
						</div>
						<div class="row">					
							<div class="col-md-4 block" data-type="container-content"></div>
							<div class="col-md-4 block" data-type="container-content"></div>
							<div class="col-md-4 block" data-type="container-content"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div></section><section><div class="row">
        <div class="col-sm-12" data-type="container-content">
        </div>
    </div></section><section><div class="row">
        <div class="col-sm-12" data-type="container-content">
        </div>
    </div></section><section><div class="row">
        <div class="col-sm-12" data-type="container-content">
        </div>
    </div></section>`

The duplication of blocks is very random and can concern each part of the HTML.

**Comment by ducdhm** [comment]
@Rilvatore I checked with the HTML content which you provided for me and I didnt get any problem with it. Please kindly debug in your side for investigating.

**Comment by Rilvatore** [comment]
We still have the issue, it happens on macs with latest chrome & safari browsers. Not on linux however. I really count on you, we don't have any clue :( do you have any idea of "hotfix" that could prevent code sections from duplicating?

**Comment by bradmac** [comment]
Can you reproduce this on a clean machine with fresh browser? Eg browserstack?

If so then to allow us to reproduce the issue please make your running code available on a public website and we can also use browserstack with the same OS and browser to reproduce the problem.

If the problem is not reproducible in browserstack, then that means the problem is due to some problem on the specific pc's you're testing with.

**Comment by Rilvatore** [comment]
Hello guys, i'm coming back with some news with my issue.
The problem could come from the Retina display from our Macs. Here is two screenshots:
![capture d ecran 2017-12-11 a 10 00 35](https://user-images.githubusercontent.com/8143609/33824866-08a9e1c6-de60-11e7-9aac-76e527803e88.png)
This screenshot is when you open the editor with a normal screen (not retina)
<br/>

<img width="1363" alt="capture d ecran 2017-12-11 a 10 01 19" src="https://user-images.githubusercontent.com/8143609/33824917-30226a34-de60-11e7-8028-abcf839e273d.png">
This one is when it's opened with a Retina screen, but when you click on the block, it becomes normal again like the previous screenshot.

It's not my initial problem (the random duplication of blocks) but it could be related.

My customer (which use your editor), send me a video to show us the problem that they have with their Macs: https://wetransfer.com/downloads/245b3dd991c44f69cb009ca5322b8be820171211093432/95ae9b

To finish, I set up a test editor (http://asd_front_preprod.ckc.asd-int.com/test-editeur/edit) you can use it if you want to test it to try to reproduce the issue.

Thank you for your responses!

**Comment by bradmac** [comment]
Thanks for the detailed info!

@ducdhm can we test with a retina display on browserstack?

**Comment by raphaelcrouzet** [comment]
Hello guys!

First of all, I would like to wish you an happy new year!
I'm comming back here to get news if you have some clues with my issue :)

If that is the case I'll be glad to get it!

Thank you!

(The previous link for the demonstration video has expired, here is a new one: https://ufile.io/it4wj)

**Comment by Rilvatore** [comment]
Hello guys!

First of all, I would like to wish you an happy new year!
I'm comming back here to get news if you have some clues with my issue :)

If that is the case I'll be glad to get it!

Thank you!

(The previous link for the demonstration video has expired, here is a new one: https://ufile.io/it4wj)

**Comment by nicolain06** [comment]
Hi guys, I have the same issue on our retinas, did you find a way to fix it?

**Comment by nicolain06** [comment]
Hello, still not working there.... any fix please?

**Comment by psasburg** [comment]
#126 Fixed it for me
