### ISSUE TITLE
[Component] Video

### ISSUE THREAD

**Issue by ducdhm** [Kademi/keditor#7]

**Comment by anhnt** [comment]
Some browser doesnt support specific video format. E.g. Firefox doesnt support playing mp4 directly https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

Needs to implement a video player like jwplayer

**Comment by anhnt** [comment]
Working example here https://rawgit.com/Kademi/keditor/master/test/test_video.html

**Comment by ducdhm** [comment]
Ratio issue

![bug_video](https://cloud.githubusercontent.com/assets/1289631/13344759/96766624-dc8b-11e5-923e-fb7b2610ff81.png)

**Comment by anhnt** [comment]
nope, i set the style: object-fit: initial

**Comment by anhnt** [comment]
anyway just changed sample video

**Comment by ducdhm** [comment]
I dont think `object-fit: initial` is good idea. Just let ratio of video be. Just set background for `video` tag is black

**Comment by bradmac** [comment]
Guys, dont worry about it because we will use jwplayer.

**Comment by ducdhm** [comment]
@bradmac OK
