### ISSUE TITLE
Unable to store & retrieve Uploaded image & Video

### ISSUE THREAD

**Issue by anuchinnu** [Kademi/keditor#70]
I have integrated this with a PHP framework. but I am unable to handle the Image & video with blob url .Taking too much time to load and and save every images.

**Comment by bradmac** [comment]
What do you mean?

**Comment by ducdhm** [comment]
@bradmac Our original photo component is saving image as based-64.

@anuchinnu You should customize photo component follow what you want. The source code of photo component is available at https://github.com/Kademi/keditor/blob/master/src/js/keditor-component-photo.js
