### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by rip747** [Kademi/keditor#74]
Is there any internal discussion about possibly implementing a test  suite like mocha in order to make sure that regression doesn't happen?

There are libraries such as drag-mock that could help with writing tests

https://www.npmjs.com/package/mocha
https://www.npmjs.com/package/drag-mock

**Comment by ducdhm** [comment]
@rip747 Probably, we have a plan to add tests for it but still have no time for it. If you don't mind, you can help us to do it ;)

**Comment by bradmac** [comment]
:+1:

**Comment by rip747** [comment]
wouldn't mind at all. I have sometime next week so I will look into it.
