### ISSUE TITLE
How to put the sidebar in a div?

### ISSUE THREAD

**Issue by titopalito** [Kademi/keditor#75]
I was trying to put the "content-area" and the "keditor-sidebar" in a "div" but I can not do it.
If someone can help me with this, I would be very thankfull.

**Comment by ducdhm** [comment]
@titopalito I have a question for you: Why do you want to put them together in a div? As in source code, `keditor-sidebar` will be append to `document.body`. However, if you want, you can request a feature to specific div for `keditor-sidebar`
