### ISSUE TITLE
Save html code from dynamic content

### ISSUE THREAD

**Issue by ivantowers** [Kademi/keditor#76]
Hello,

Im new using keditor and not an expert for javascript....

How to save the HTML code generated for a dynamic content component??

I create a file for a dinamyc content "_dynamic_content.php" inside this file i have this code:

```
<?php 
echo $_GET['data-article'];
?>
```

In the editor shows the text:

"article01"

Text passed by the dynamic component "data-article="article01"".

Then i create a function in javascript to generate the code:

function Save() {	
	document.getElementById("Website").value=$('#keditor1').keditor('getContent');
}

("Website" is a textarea )

The generated code is this:

```
<section><div class="row">
<div class="col-sm-12" data-type="container-content">
<section data-type="component-nonExisting" data-website="website01" data-blog="blog01" data-article="article01" data-tags="tag01,tag02"><div data-dynamic-href="snippets/default/_dynamic_content.php" id="keditor-dynamic-element-1509662283364"></div></section></div>
</div>
</section>

```

In this case must show "article01" but this code does not show any results. How i can save the html code generated by the php file?? or in any case show the text.

Thanks you!!

**Comment by ducdhm** [comment]
@ivantowers As original concept of dynamic element, it's always dynamic so whenever you load content with dynamic element, you're always need to load content for it. There are 2 ways to do it:
 1. Via server: You can add code in your server-side for detecting dynamic component with attribute `data-dynamic-href` and generate content for it
 2. Via client: You can add js code (not in editor page) for getting data via AJAX.
