### ISSUE TITLE
Unclosed img tag

### ISSUE THREAD

**Issue by titopalito** [Kademi/keditor#77]
Hello,
Actually i'm programming in JSF and saw that the img tag is unclosed like this:
`<img style="example">` and it causes crashes when i try to run a page with pre-loaded content.
Can you tell me how to resolve the problem? 
I'll appreciate your patience. 
Thanks a lot.

**Comment by ducdhm** [comment]
@titopalito You can change to `<img style="example" />` and change the doctype of your website too.
