### ISSUE TITLE
Add src\css to ignore list

### ISSUE THREAD

**Issue by rip747** [Kademi/keditor#80]
I don't see why these were tracked since they are generated after being compiled. I currently ignore them in my branch

**Comment by ducdhm** [comment]
@rip747 `dist` directories for releasing. When I public a release, I'll build dist with latest version number. There are a lot of developers which they really don't care about LESS, gulp, etc... related to development. They just need final js and css files.

About `src\css` directories, I'll add it in gitignore, it's just for development
