### ISSUE TITLE
Not able to add more than three content area

### ISSUE THREAD

**Issue by aref-lazrek** [Kademi/keditor#81]
First I appreciate this great work
the issue happen when adding more than three content area

` 
        <script type="text/javascript">
            $(function() {
                $('#content-area1, #content-area2, #content-area3, #content-area4, #content-area5').keditor();
            });
        </script>`

**Comment by aref-lazrek** [comment]
the problem happen when there is no contentareaselector in opyion, I solved it by adding
`        var contentAreas=target;` on line 906

**Comment by ducdhm** [comment]
@aref-lazrek The concept of keditor is `$('target').keditor({contentAreasSelector: 'selector1, selector2, etc...'})`. It means your `$('target')` will contains content area. You dont need to change anything, just need to wrap all your content area by a div and initializing keditor for this div and specific `contentAreasSelector` for it.
