### ISSUE TITLE
CKEditor not working when using iframe mode

### ISSUE THREAD

**Issue by Jordy-A** [Kademi/keditor#83]
When using the iframe mode, the ckeditor is not working properly. For instance, because the utf charset is not set, weird characters are shown when using page breaks. And, also, there are some other things not working: for instance, when adding more than one section, you can't select text anymore and make them bold or do something else.

I think, this can be fixed by sending the ckeditor javascript to the iframe as well.

**Comment by ducdhm** [comment]
@Jordy-A Can you give me more details about this issue? Maybe live code?

**Comment by ducdhm** [comment]
No details, so I close this issue.
