### ISSUE TITLE
 #feature | Custom css of my components/snippet

### ISSUE THREAD

**Issue by eliooses** [Kademi/keditor#85]
I need the possibility of edit the BG color/imager, etc. of my components. I know what is not hard with JS.

I will try to do this, but if someone else already made it please let me know and add to the project.

Thanks in advance.

**Comment by ducdhm** [comment]
@eliooses If you're still finding out the solution or code example for it, I'll implement an example for changing background color and image for container at https://github.com/Kademi/keditor/issues/98

**Comment by eliooses** [comment]
Hi there @ducdhm !

Yes, I still finding out this solution.

Thanks a lot in advance.
