### ISSUE TITLE
I want to add new components. Can you please help me with that? A list of steps would do fine.

### ISSUE THREAD

**Issue by 01AbhaY** [Kademi/keditor#87]

**Comment by ducdhm** [comment]
Hi @01AbhaY, please do the following:
 * Firstly, you need to add new snippet for new component. The guide is [here](https://github.com/Kademi/keditor#customize-snippet)
 * Secondly, you need to add handle for new component. The guide is [here](https://github.com/Kademi/keditor#customize-component-type)

Please let me know if you have other questions
