### ISSUE TITLE
How save content-area after edit text?? 

### ISSUE THREAD

**Issue by baldolfo** [Kademi/keditor#89]
Save button does not exist... 
How can I put it?  With ckeditor inlinesave does not work

**Comment by ducdhm** [comment]
hi @baldolfo, you can user `$('#id').keditor('getContent');` to get entire content of content-area. And then, you need server-side stuff to store this content.

**Comment by baldolfo** [comment]
Thank.... but i think is difficult . Php is hard for me........

**Comment by ducdhm** [comment]
Hi @baldolfo, it's PHP stuff is not related to Keditor. We just take care of JS stuff only. So I'll close this issue. Hope you can find the solution for yourself with PHP
