### ISSUE TITLE
[Request] Drag Container on Container

### ISSUE THREAD

**Issue by nev3rmi** [Kademi/keditor#91]
I want to load drag container inside another container could you please provide this, so it will be very helpful to create the layout for the page.

Thanks you :)

**Comment by ducdhm** [comment]
@nev3rmi We already implemented this feature at https://github.com/Kademi/keditor/issues/68. We also publish this feature in v1.1.5 (https://github.com/Kademi/keditor/releases/tag/1.1.5)

**Comment by nev3rmi** [comment]
Do you have any example, I try it but seem like not working???

**Comment by ducdhm** [comment]
@nev3rmi What do you mean not working?

**Comment by nev3rmi** [comment]
This one worked already thanks for your support :) please closed this
