### ISSUE TITLE
[Issues] Could you please check the dynamically content

### ISSUE THREAD

**Issue by nev3rmi** [Kademi/keditor#92]
It seems not work on my side. After I get the content and save it to db, after I retrieve the content, nothing happens if it is the dynamic content.

**Comment by joakim-emagine** [comment]
I am having that same issue, trying to figure out how to trigger the content loading on the frontend. I have already included the required Js files.

**Comment by joakim-emagine** [comment]
> @ivantowers As original concept of dynamic element, it's always dynamic so whenever you load content with dynamic element, you're always need to load content for it. There are 2 ways to do it:

> Via server: You can add code in your server-side for detecting dynamic component with attribute data-dynamic-href and generate content for it
Via client: You can add js code (not in editor page) for getting data via AJAX.

From closed issue #76 

I used the via client option of just initiating Ajax call
```
	$.ajax({
				url: '<?php echo $element[1];?>',
				type: 'GET',
				dataType: 'HTML',
				success: function (response, status, xhr) {
					dynamicElement.html(response);
				
				},
				error: function (response, status, xhr) {
					
				}
			});
```

**Comment by nev3rmi** [comment]
I create a new component and trigger it by $.jquery load

**Comment by ducdhm** [comment]
@joakim-emagine @nev3rmi Original concept of dynamic component is making component's content *dynamic* and *always dynamic*. In `Editing mode`, Keditor automatically loads dynamic component from `data-dynamic-href` with addition params from `data-*` attributes. So in `Reading mode` or frontend, your server need to handle the content of these dynamic components.

**Comment by nev3rmi** [comment]
So you mean the kEditor didn't do anything in the reading mode @@? am I right ?

**Comment by ducdhm** [comment]
@nev3rmi Keditor means it's a editor. It just takes care of editing stuff, not reading mode. The name of it is so meaningful.

**Comment by nev3rmi** [comment]
ok then I gonna do the component for dynamic content ^^
