### ISSUE TITLE
[Modified Features] Load Multiple Components 

### ISSUE THREAD

**Issue by nev3rmi** [Kademi/keditor#93]
It is really difficult to modify the keditor-components-xxx.js when it become large, so I modify the code and make it a lot of easier.

If this feature exist please ignore it :)

The new folder gonna add in is: components

And all the files inside the folder will be loaded.

In keditor.js have 2 variables is necessary:

Line 81: componentName: // Type: [ARRAY] This will be the name files
Line 97: componentDir: // Directory of the files

Also have some additional snippets :) hope It help you guys.

Download File [HERE](https://github.com/Kademi/keditor/files/1649486/js.zip)

**Comment by Williammonte7** [comment]
I could not install, have to send link, already installed please? 
another question, these new components work (component-carousel-v2, component-360view, component-iframe )

**Comment by nev3rmi** [comment]
Did you include all the necessary files ?

**Comment by Williammonte7** [comment]
I tried to install the files but i could not, I would like to see if you can send me files for download already installed ? I thank

**Comment by ducdhm** [comment]
Hi @nev3rmi, keditor-components-xxx.js is just standard or plain components which Keditor provides for developers to image how to create components. In real world, you can use server-side to merge all your components into a file and include this file into your website.

**Comment by nev3rmi** [comment]
@ducdhm:
Hi, actually I like the ideas to keep all components separate :)

@Williammonte7:

Hi, can you show me the error so then I can help you :)

Did you change those yet ?

```
componentName: [ // File name
            "component-360view.js",
            "component-audio.js",
            "component-carousel-v2.js",
            "component-carousel.js",
            "component-ckeditorFull.js",
            "component-googleMap.js",
            "component-iframe.js",
            "component-jqueryEditor.js",
            "component-photo.js",
            "component-text.js",
            "component-video.js",
            "component-vimeo.js",
            "component-x.js",
            "component-youtube.js",
        ],
        componentDir: '/views/cms/js/components/',
```

**Comment by nev3rmi** [comment]
@Williammonte7:

https://picks.work/dev/lab/keditor/examples/blank.html

Full loaded :)
[keditor.zip](https://github.com/Kademi/keditor/files/1757053/keditor.zip)

**Comment by ducdhm** [comment]
@nev3rmi But it'll take more time to load components via AJAX. If you still want to do it, you can fork and change :)

**Comment by nev3rmi** [comment]
just field second but It to manage code It better :)

**Comment by ducdhm** [comment]
@nev3rmi I think you misunderstood between dev and prod mode.
 * In dev mode, you really need a good structure to manage and maintain your code. So you can separate your components in to folders/sub folders
 * But in prod mode, end-users, they dont care about how you manage or maintain your code. They just care your editor is loaded fast or slow. By separating components into small parts in prod mode, it'll take a while for loading all your components completely. It's can be fast when you have a few components like 5-10. But how about 50-100 components? 

Btw, it's great when you're interested in KEditor. It's MIT project so you can fork and do anything you want in your forked repo. 
Thanks!
/Duc

**Comment by nev3rmi** [comment]
Thanks you ^^, I really like this plugin haha
